### ISSUE TITLE
java.lang.NoSuchMethodError: sun.awt.AWTAccessor.getMouseEventAccessor()Lsun/awt/AWTAccessor$MouseEventAccessor;

### ISSUE THREAD

**Issue by pmouawad** [weisJ/darklaf#133]
Using JMeter, I try to open a file.
I list by name, try to go into a folder and I get this.

Stacktrace:

`2020-04-09 15:27:38,378 ERROR o.a.j.JMeter: Uncaught exception in thread Thread[AWT-EventQueue-0,6,main]
java.lang.NoSuchMethodError: sun.awt.AWTAccessor.getMouseEventAccessor()Lsun/awt/AWTAccessor$MouseEventAccessor;
	at com.github.weisj.darklaf.ui.filechooser.DarkFilePane$DarkHandler.mouseClicked(DarkFilePane.java:434) ~[darklaf-core-1.4.3.1.jar:1.4.3.1]
	at java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:270) ~[?:1.8.0_161]
	at java.awt.Component.processMouseEvent(Component.java:6536) ~[?:1.8.0_161]
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324) ~[?:1.8.0_161]
	at java.awt.Component.processEvent(Component.java:6298) ~[?:1.8.0_161]
	at java.awt.Container.processEvent(Container.java:2237) ~[?:1.8.0_161]
	at java.awt.Component.dispatchEventImpl(Component.java:4889) ~[?:1.8.0_161]
	at java.awt.Container.dispatchEventImpl(Container.java:2295) ~[?:1.8.0_161]
	at java.awt.Component.dispatchEvent(Component.java:4711) ~[?:1.8.0_161]
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889) ~[?:1.8.0_161]
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535) ~[?:1.8.0_161]
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467) ~[?:1.8.0_161]
	at java.awt.Container.dispatchEventImpl(Container.java:2281) ~[?:1.8.0_161]
	at java.awt.Window.dispatchEventImpl(Window.java:2746) ~[?:1.8.0_161]
	at java.awt.Component.dispatchEvent(Component.java:4711) ~[?:1.8.0_161]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758) ~[?:1.8.0_161]
	at java.awt.EventQueue.access$500(EventQueue.java:97) ~[?:1.8.0_161]
	at java.awt.EventQueue$3.run(EventQueue.java:709) ~[?:1.8.0_161]
	at java.awt.EventQueue$3.run(EventQueue.java:703) ~[?:1.8.0_161]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_161]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80) ~[?:1.8.0_161]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90) ~[?:1.8.0_161]
	at java.awt.EventQueue$4.run(EventQueue.java:731) ~[?:1.8.0_161]
	at java.awt.EventQueue$4.run(EventQueue.java:729) ~[?:1.8.0_161]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_161]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80) ~[?:1.8.0_161]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728) ~[?:1.8.0_161]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) ~[?:1.8.0_161]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) ~[?:1.8.0_161]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109) ~[?:1.8.0_161]
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190) ~[?:1.8.0_161]
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235) ~[?:1.8.0_161]
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233) ~[?:1.8.0_161]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_161]
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233) ~[?:1.8.0_161]
	at java.awt.Dialog.show(Dialog.java:1084) ~[?:1.8.0_161]
	at javax.swing.JFileChooser.showDialog(JFileChooser.java:758) ~[?:1.8.0_161]
	at javax.swing.JFileChooser.showOpenDialog(JFileChooser.java:656) ~[?:1.8.0_161]
	at org.apache.jmeter.gui.util.FileDialoger.promptToOpenFile(FileDialoger.java:196) ~[ApacheJMeter_core.jar:5.3-SNAPSHOT]
	at org.apache.jmeter.gui.util.FileDialoger.promptToOpenFile(FileDialoger.java:161) ~[ApacheJMeter_core.jar:5.3-SNAPSHOT]
	at org.apache.jmeter.gui.util.FileDialoger.promptToOpenFile(FileDialoger.java:140) ~[ApacheJMeter_core.jar:5.3-SNAPSHOT]
	at org.apache.jmeter.gui.util.FileDialoger.promptToOpenFile(FileDialoger.java:120) ~[ApacheJMeter_core.jar:5.3-SNAPSHOT]
	at org.apache.jmeter.gui.action.Load.doActionAfterCheck(Load.java:75) ~[ApacheJMeter_core.jar:5.3-SNAPSHOT]
	at org.apache.jmeter.gui.action.AbstractActionWithNoRunningTest.doAction(AbstractActionWithNoRunningTest.java:44) ~[ApacheJMeter_core.jar:5.3-SNAPSHOT]
	at org.apache.jmeter.gui.action.ActionRouter.performAction(ActionRouter.java:87) ~[ApacheJMeter_core.jar:5.3-SNAPSHOT]
	at org.apache.jmeter.gui.action.ActionRouter.lambda$actionPerformed$0(ActionRouter.java:69) ~[ApacheJMeter_core.jar:5.3-SNAPSHOT]
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311) [?:1.8.0_161]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756) [?:1.8.0_161]
	at java.awt.EventQueue.access$500(EventQueue.java:97) [?:1.8.0_161]
	at java.awt.EventQueue$3.run(EventQueue.java:709) [?:1.8.0_161]
	at java.awt.EventQueue$3.run(EventQueue.java:703) [?:1.8.0_161]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_161]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80) [?:1.8.0_161]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726) [?:1.8.0_161]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) [?:1.8.0_161]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [?:1.8.0_161]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [?:1.8.0_161]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:1.8.0_161]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [?:1.8.0_161]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [?:1.8.0_161]`

**Comment by pmouawad** [comment]
Note I am using MacOSX with jdk1.8.0_161

**Comment by weisJ** [comment]
I see. Looks I have been using a version of the 1.8jdk that actually has this method present. I guess I'll just delete it, as I doubt there is much need for touch support.

**Comment by vlsi** [comment]
`javax.swing.SwingUtilities#convertMouseEvent` seems to perform `setCausedByTouchEvent`
So I guess this `sun....` API could be replaced with `javax.swing.SwingUtilities`

**Comment by weisJ** [comment]
How important would you rate this fix? Can this wait for the next release or should I release a fix version based on `1.4.3.1`?

**Comment by pmouawad** [comment]
Hello,
Well it blocks jmeter release for sure.

Regards

**Comment by weisJ** [comment]
After #127 has been merged. There’s I’ll iron out some problems that may occur. After that I can release. So should be doable this week.

**Comment by weisJ** [comment]
Fixed in 6ae3a7c002a2713928437196cd52a1aa70fe1dae
