### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: -1

### ISSUE THREAD

**Issue by pmouawad** [weisJ/darklaf#135]
Hello,
Using JMeter with darklaf on MacOSX I got this errror today.

Unfortunately I cannot give the exact scenario for it, it happens on repaint 

Stacktrace:

`2020-04-10 16:16:19,586 ERROR o.a.j.JMeter: Uncaught exception in thread Thread[AWT-EventQueue-0,6,main]
java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.Vector.elementData(Vector.java:737) ~[?:1.8.0_201]
	at java.util.Vector.elementAt(Vector.java:480) ~[?:1.8.0_201]
	at javax.swing.tree.DefaultMutableTreeNode.getChildAt(DefaultMutableTreeNode.java:245) ~[?:1.8.0_201]
	at javax.swing.tree.DefaultTreeModel.getChild(DefaultTreeModel.java:174) ~[?:1.8.0_201]
	at com.github.weisj.darklaf.ui.tree.DarkTreeUI.paintVerticalPartOfLeg(DarkTreeUI.java:672) ~[darklaf-core-1.4.3.1.jar:1.4.3.1]
	at com.github.weisj.darklaf.ui.tree.DarkTreeUI.paint(DarkTreeUI.java:456) ~[darklaf-core-1.4.3.1.jar:1.4.3.1]
	at javax.swing.plaf.ComponentUI.update(ComponentUI.java:161) ~[?:1.8.0_201]
	at javax.swing.JComponent.paintComponent(JComponent.java:780) ~[?:1.8.0_201]
	at javax.swing.JComponent.paint(JComponent.java:1056) ~[?:1.8.0_201]
	at javax.swing.JComponent.paintToOffscreen(JComponent.java:5210) ~[?:1.8.0_201]
	at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1579) ~[?:1.8.0_201]
	at javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1502) ~[?:1.8.0_201]
	at javax.swing.RepaintManager.paint(RepaintManager.java:1272) ~[?:1.8.0_201]
	at javax.swing.JComponent._paintImmediately(JComponent.java:5158) ~[?:1.8.0_201]
	at javax.swing.JComponent.paintImmediately(JComponent.java:4969) ~[?:1.8.0_201]
	at javax.swing.RepaintManager$4.run(RepaintManager.java:831) ~[?:1.8.0_201]
	at javax.swing.RepaintManager$4.run(RepaintManager.java:814) ~[?:1.8.0_201]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_201]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74) ~[?:1.8.0_201]
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:814) ~[?:1.8.0_201]
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:789) ~[?:1.8.0_201]
	at javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:738) ~[?:1.8.0_201]
	at javax.swing.RepaintManager.access$1200(RepaintManager.java:64) ~[?:1.8.0_201]
	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1732) ~[?:1.8.0_201]
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311) ~[?:1.8.0_201]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758) ~[?:1.8.0_201]
	at java.awt.EventQueue.access$500(EventQueue.java:97) ~[?:1.8.0_201]
	at java.awt.EventQueue$3.run(EventQueue.java:709) ~[?:1.8.0_201]
	at java.awt.EventQueue$3.run(EventQueue.java:703) ~[?:1.8.0_201]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_201]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74) ~[?:1.8.0_201]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728) ~[?:1.8.0_201]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205) [?:1.8.0_201]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [?:1.8.0_201]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [?:1.8.0_201]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:1.8.0_201]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [?:1.8.0_201]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [?:1.8.0_201]`

**Comment by weisJ** [comment]
How to reproduce:
````java
        DefaultMutableTreeNode root = new DefaultMutableTreeNode("Root");
        DefaultMutableTreeNode node = new DefaultMutableTreeNode("Node");
        root.add(node);
        JTree tree = new JTree(root) {
            @Override
            public boolean isExpanded(final TreePath path) {
                return true;
            }
        };
````
I guess somewhere in your tree there is a node that has no children but is expanded (even though that shouldn't be possible).

**Comment by pmouawad** [comment]
Hello @weisJ ,
it looks weird as this does not seem possible on JMeter.
Will double check.
Thanks

**Comment by pmouawad** [comment]
Thanks for fix.
When do you plan to release ? Thanks

**Comment by weisJ** [comment]
I'll need confirmation that the selection colour does indeed changes appropriately.  Then I'll be ready to merge #127 and release the new version.
