### ISSUE TITLE
NPE when using JFileChooser

### ISSUE THREAD

**Issue by pmouawad** [weisJ/darklaf#157]
**Describe the bug**

Stacktrace:

`2020-05-01 00:00:18,270 ERROR o.a.j.JMeter: Uncaught exception in thread Thread[AWT-EventQueue-0,6,main]
java.lang.ExceptionInInitializerError: null
	at org.apache.jmeter.gui.action.Save.computeFileName(Save.java:202) ~[ApacheJMeter_core.jar:5.3-SNAPSHOT]
	at org.apache.jmeter.gui.action.Save.doAction(Save.java:164) ~[ApacheJMeter_core.jar:5.3-SNAPSHOT]
	at org.apache.jmeter.gui.action.ActionRouter.performAction(ActionRouter.java:87) ~[ApacheJMeter_core.jar:5.3-SNAPSHOT]
	at org.apache.jmeter.gui.action.ActionRouter.lambda$actionPerformed$0(ActionRouter.java:69) ~[ApacheJMeter_core.jar:5.3-SNAPSHOT]
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311) ~[?:1.8.0_201]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758) ~[?:1.8.0_201]
	at java.awt.EventQueue.access$500(EventQueue.java:97) ~[?:1.8.0_201]
	at java.awt.EventQueue$3.run(EventQueue.java:709) ~[?:1.8.0_201]
	at java.awt.EventQueue$3.run(EventQueue.java:703) ~[?:1.8.0_201]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_201]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74) ~[?:1.8.0_201]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728) ~[?:1.8.0_201]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205) [?:1.8.0_201]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [?:1.8.0_201]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [?:1.8.0_201]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:1.8.0_201]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [?:1.8.0_201]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [?:1.8.0_201]
Caused by: java.lang.NullPointerException
	at com.github.weisj.darklaf.components.tooltip.TooltipAwareButton.getToolTipContext(TooltipAwareButton.java:69) ~[darklaf-core-2.1.0.jar:2.1.0]
	at com.github.weisj.darklaf.components.tooltip.TooltipAwareButton.updateUI(TooltipAwareButton.java:62) ~[darklaf-core-2.1.0.jar:2.1.0]
	at javax.swing.AbstractButton.init(AbstractButton.java:2176) ~[?:1.8.0_201]
	at javax.swing.JButton.<init>(JButton.java:137) ~[?:1.8.0_201]
	at javax.swing.JButton.<init>(JButton.java:91) ~[?:1.8.0_201]
	at javax.swing.JButton.<init>(JButton.java:122) ~[?:1.8.0_201]
	at com.github.weisj.darklaf.components.tooltip.TooltipAwareButton.<init>(TooltipAwareButton.java:57) ~[darklaf-core-2.1.0.jar:2.1.0]
	at com.github.weisj.darklaf.ui.filechooser.DarkFileChooserUI.createUpFolderButton(DarkFileChooserUI.java:317) ~[darklaf-core-2.1.0.jar:2.1.0]
	at com.github.weisj.darklaf.ui.filechooser.DarkFileChooserUI.createTopButtonArea(DarkFileChooserUI.java:262) ~[darklaf-core-2.1.0.jar:2.1.0]
	at com.github.weisj.darklaf.ui.filechooser.DarkFileChooserUI.createTopPanel(DarkFileChooserUI.java:236) ~[darklaf-core-2.1.0.jar:2.1.0]
	at com.github.weisj.darklaf.ui.filechooser.DarkFileChooserUI.installComponents(DarkFileChooserUI.java:90) ~[darklaf-core-2.1.0.jar:2.1.0]
	at javax.swing.plaf.basic.BasicFileChooserUI.installUI(BasicFileChooserUI.java:173) ~[?:1.8.0_201]
	at com.github.weisj.darklaf.ui.filechooser.DarkFileChooserUIBridge.installUI(DarkFileChooserUIBridge.java:137) ~[darklaf-core-2.1.0.jar:2.1.0]
	at javax.swing.JComponent.setUI(JComponent.java:666) ~[?:1.8.0_201]
	at javax.swing.JFileChooser.updateUI(JFileChooser.java:1836) ~[?:1.8.0_201]
	at javax.swing.JFileChooser.setup(JFileChooser.java:371) ~[?:1.8.0_201]
	at javax.swing.JFileChooser.<init>(JFileChooser.java:343) ~[?:1.8.0_201]
	at javax.swing.JFileChooser.<init>(JFileChooser.java:296) ~[?:1.8.0_201]
	at org.apache.jmeter.gui.util.FileDialoger.<clinit>(FileDialoger.java:42) ~[ApacheJMeter_core.jar:5.3-SNAPSHOT]
	... 18 more
`

**To Reproduce**

Download :
https://builds.apache.org/job/JMeter-trunk/7733/

Run jmeter
File > Save Test plan as
You get the NPE

**Additional Information:**
 - OS: macOS
 - OS Version: 10.11.6
- Darklaf Version: 2.1.0

**Additional context**

**Comment by pmouawad** [comment]
Thanks for fix, it works
