### ISSUE TITLE
[Feature Request] Closable JTabbedPane

### ISSUE THREAD

**Issue by GraxCode** [weisJ/darklaf#181]
**General description**
As there is no default closable JTabbedPane in swing it would be nice to have one. I'm sure this feature is needed often, and making a custom JTabbedPane that looks good in themed darklaf is hard.

This suggestion is:
- [x] Visual
- [x] Behavioral

**For visual suggestions**
Just like a normal JTabbedPane, but with a rounded "X" button on the right. 
![Screenshot](https://user-images.githubusercontent.com/24767548/84372820-026bde80-abdc-11ea-8228-e06e9a641e7f.png)

**For behavioral suggestions**
When clicking the X, the tab should be removed.

**Comment by weisJ** [comment]
There already is `ClosableTabbedPane`. Although the implementation was a bit rough. I have cleaned it up and improved the icon/spacing a bit.

You can always try out the latest snapshot build using
````kotlin
repositories {
    maven {
        url = uri("https://oss.sonatype.org/content/repositories/snapshots/")
    }
}

configurations.all {
    resolutionStrategy.cacheChangingModulesFor(0, "seconds")
}

dependencies {
    implementation("com.github.weisj:darklaf-core:latest.integration")
}
````

**Comment by GraxCode** [comment]
Very cool! It would be nice if the docs contained something about it. Thanks!

**Comment by weisJ** [comment]
I'll see to updated the wiki with the missing information.

**Comment by GraxCode** [comment]
Is there a feature that allows only certain tabs to be closable?

**Comment by GraxCode** [comment]
Also when using DnD and dragging to the first index:
```java
java.lang.IndexOutOfBoundsException: Index: -1, Tab count: 4
	at java.desktop/javax.swing.JTabbedPane.checkIndex(JTabbedPane.java:1791)
	at java.desktop/javax.swing.JTabbedPane.getBoundsAt(JTabbedPane.java:1328)
	at com.github.weisj.darklaf.ui.tabbedpane.TabbedPaneUtil.calculateDropRectWrapLayout(TabbedPaneUtil.java:195)
	at com.github.weisj.darklaf.ui.tabbedpane.TabbedPaneUtil.getDropRect(TabbedPaneUtil.java:128)
	at com.github.weisj.darklaf.ui.tabbedpane.TabbedPaneTransferHandler.dragOver(TabbedPaneTransferHandler.java:224)
	at java.desktop/javax.swing.TransferHandler$SwingDropTarget.dragOver(TransferHandler.java:1255)
	at java.desktop/sun.awt.dnd.SunDropTargetContextPeer.processMotionMessage(SunDropTargetContextPeer.java:482)
	at java.desktop/sun.awt.dnd.SunDropTargetContextPeer$EventDispatcher.dispatchMotionEvent(SunDropTargetContextPeer.java:835)
	at java.desktop/sun.awt.dnd.SunDropTargetContextPeer$EventDispatcher.dispatchEvent(SunDropTargetContextPeer.java:781)
	at java.desktop/sun.awt.dnd.SunDropTargetEvent.dispatch(SunDropTargetEvent.java:48)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4877)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4919)
	at java.desktop/java.awt.LightweightDispatcher.processDropTargetEvent(Container.java:4622)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4484)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2764)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by weisJ** [comment]
> Is there a feature that allows only certain tabs to be closable?

Currently not. Do you want
1. The close button to be disabled.
2. The close button not visible but still taking up space.
3. The close button not visible without taking up space.

> Also when using DnD and dragging to the first index

Thanks fore reporting. I see that you are using WrapLayout. I would advise to use ScrollLayout as that’s the most optimised (It will essentially behave exactly as the tabbed pane for the editor in IntelliJ does).

**Comment by GraxCode** [comment]
> 
> 
> > Is there a feature that allows only certain tabs to be closable?
> 
> Currently not. Do you want
> 
>     1. The close button to be disabled.
> 
>     2. The close button not visible but still taking up space.
> 
>     3. The close button not visible without taking up space.
> 
> 
> > Also when using DnD and dragging to the first index
> 
> Thanks fore reporting. I see that you are using WrapLayout. I would advise to use ScrollLayout as that’s the most optimised (It will essentially behave exactly as the tabbed pane for the editor in IntelliJ does).

Thanks for your tips. I want a tab that is completely unclosable (without a close button and space for it, so actually a tab like in a normal JTabbedPane inside a ClosableTabbedPane).

**Comment by weisJ** [comment]
The NPE should be fixed now.
I have added an API for making tabs closable on a per tab basis. You can try it out with the latest snapshot build.

**Comment by GraxCode** [comment]
Thank you, very cool!
