### ISSUE TITLE
NPE in javax.swing.ToolTipManager.initiateToolTip(ToolTipManager.java:478) ~[?:1.8.0_201]

### ISSUE THREAD

**Issue by pmouawad** [weisJ/darklaf#183]
Describe the bug
Steps to reproduce:

    Download JMeter nightly, extract it.
    Open the Jmeter and set the look and feel to Darklaf-IntelliJ
    Open any script
    Try to expand the threadgroup
    The log will have the exception

There is no error displayed on the UI and the functionality didn't break.

To Reproduce
Please provide a minimal example to reproduce the issue or if one of the provided demos can be used
reference it.

Screenshots

Additional Information:

Java.version=1.8.0_201
java.vm.name=Java HotSpot(TM) 64-Bit Server VM
os.name=Mac OS X
os.arch=x86_64
os.version=10.11.6

    Darklaf Version: 2.2.1

Additional context
Using JMeter nightly build updated with 2.2.1

Exception:

`2020-06-13 13:53:24,914 ERROR o.a.j.JMeter: Uncaught exception in thread Thread[AWT-EventQueue-0,6,main]
java.lang.NullPointerException: null
	at javax.swing.ToolTipManager.initiateToolTip(ToolTipManager.java:478) ~[?:1.8.0_201]
	at javax.swing.ToolTipManager.mouseEntered(ToolTipManager.java:435) ~[?:1.8.0_201]
	at java.awt.AWTEventMulticaster.mouseEntered(AWTEventMulticaster.java:300) ~[?:1.8.0_201]
	at java.awt.AWTEventMulticaster.mouseEntered(AWTEventMulticaster.java:299) ~[?:1.8.0_201]
	at java.awt.AWTEventMulticaster.mouseEntered(AWTEventMulticaster.java:299) ~[?:1.8.0_201]
	at java.awt.AWTEventMulticaster.mouseEntered(AWTEventMulticaster.java:299) ~[?:1.8.0_201]
	at java.awt.AWTEventMulticaster.mouseEntered(AWTEventMulticaster.java:299) ~[?:1.8.0_201]
	at java.awt.AWTEventMulticaster.mouseEntered(AWTEventMulticaster.java:299) ~[?:1.8.0_201]
	at java.awt.AWTEventMulticaster.mouseEntered(AWTEventMulticaster.java:299) ~[?:1.8.0_201]
	at java.awt.AWTEventMulticaster.mouseEntered(AWTEventMulticaster.java:299) ~[?:1.8.0_201]
	at java.awt.AWTEventMulticaster.mouseEntered(AWTEventMulticaster.java:299) ~[?:1.8.0_201]
	at java.awt.AWTEventMulticaster.mouseEntered(AWTEventMulticaster.java:299) ~[?:1.8.0_201]
	at java.awt.AWTEventMulticaster.mouseEntered(AWTEventMulticaster.java:299) ~[?:1.8.0_201]
	at java.awt.AWTEventMulticaster.mouseEntered(AWTEventMulticaster.java:299) ~[?:1.8.0_201]
	at java.awt.Component.processMouseEvent(Component.java:6548) ~[?:1.8.0_201]
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324) ~[?:1.8.0_201]
	at java.awt.Component.processEvent(Component.java:6304) ~[?:1.8.0_201]
	at java.awt.Container.processEvent(Container.java:2239) ~[?:1.8.0_201]
	at java.awt.Component.dispatchEventImpl(Component.java:4889) ~[?:1.8.0_201]
	at java.awt.Container.dispatchEventImpl(Container.java:2297) ~[?:1.8.0_201]
	at java.awt.Component.dispatchEvent(Component.java:4711) ~[?:1.8.0_201]
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904) ~[?:1.8.0_201]
	at java.awt.LightweightDispatcher.retargetMouseEnterExit(Container.java:4686) ~[?:1.8.0_201]
	at java.awt.LightweightDispatcher.trackMouseEnterExit(Container.java:4664) ~[?:1.8.0_201]
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4515) ~[?:1.8.0_201]
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476) ~[?:1.8.0_201]
	at java.awt.Container.dispatchEventImpl(Container.java:2283) ~[?:1.8.0_201]
	at java.awt.Window.dispatchEventImpl(Window.java:2746) ~[?:1.8.0_201]
	at java.awt.Component.dispatchEvent(Component.java:4711) ~[?:1.8.0_201]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760) ~[?:1.8.0_201]
	at java.awt.EventQueue.access$500(EventQueue.java:97) ~[?:1.8.0_201]
	at java.awt.EventQueue$3.run(EventQueue.java:709) ~[?:1.8.0_201]
	at java.awt.EventQueue$3.run(EventQueue.java:703) ~[?:1.8.0_201]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_201]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74) ~[?:1.8.0_201]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84) ~[?:1.8.0_201]
	at java.awt.EventQueue$4.run(EventQueue.java:733) ~[?:1.8.0_201]
	at java.awt.EventQueue$4.run(EventQueue.java:731) ~[?:1.8.0_201]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_201]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74) ~[?:1.8.0_201]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730) ~[?:1.8.0_201]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205) [?:1.8.0_201]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [?:1.8.0_201]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [?:1.8.0_201]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:1.8.0_201]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [?:1.8.0_201]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [?:1.8.0_201]`

**Comment by weisJ** [comment]
Very strange. It looks like the component reports a tiptext of `null`. Though this shouldn't be possible.
Also it doesn't really look like darklaf is at play here. Does the component override the `JComponent.getToolTipText(MouseEvent)` method?

**Comment by weisJ** [comment]
Please try to return an empty string instead of `null` in this method

````java

        JTree treevar = new JTree(treeModel) {
            private static final long serialVersionUID = 240L;

            @Override
            public String getToolTipText(MouseEvent event) {
                TreePath path = this.getPathForLocation(event.getX(), event.getY());
                if (path != null) {
                    Object treeNode = path.getLastPathComponent();
                    if (treeNode instanceof DefaultMutableTreeNode) {
                        Object testElement = ((DefaultMutableTreeNode) treeNode).getUserObject();
                        if (testElement instanceof TestElement) {
                            String comment = ((TestElement) testElement).getComment();
                            if (comment != null && comment.length() > 0) {
                                return comment;
                            }
                        }
                    }
                }
                return null;
            }
        };
````

**Comment by pmouawad** [comment]
@weisJ , thanks for tip.
But why It does not break in other LAFs ?
Javadoc contract says to return null if event is null.
But it does not says not to return null if path for location is null no ? so would you say we are violating contract ?

Thanks

**Comment by weisJ** [comment]
Actually I'm not sure why it doesn't happen in other lafs. The culprit statement is
````java
String newToolTipText = component.getToolTipText(event);
Point newPreferredLocation = component.getToolTipLocation(event);
boolean sameLoc = (preferredLocation != null) ?
    preferredLocation.equals(newPreferredLocation) :
    (newPreferredLocation == null);

if (!sameComponent || !toolTipText.equals(newToolTipText) //<-- Happens here if tiptext is null
    || !sameLoc) {
    toolTipText = newToolTipText;
    preferredLocation = newPreferredLocation;
    showTipWindow();
}
````

In newer versions of the JDK this is acutally replaced by
`Objects.equals(toolTipText, newToolTipText)`.

What is the exact wording for the contract? The javadoc says
`````
Returns the string to be used as the tooltip for event. By default this returns any string set using setToolTipText. If a component provides more extensive API to support differing tooltips at different locations, this method should be overridden.
````
Doesn't mention that the tiptext should be `null` if the event is `null`.

**Comment by pmouawad** [comment]
Returns 
<img width="876" alt="Screen Shot 2020-06-13 at 20 38 50" src="https://user-images.githubusercontent.com/3127467/84576560-e9b72080-adb5-11ea-929b-28549cb184c2.png">
a string containing the tooltip or null if event is null

**Comment by weisJ** [comment]
Would you mind to share a script file with which the error is reproducible. I can't seem to get it to happen for me.

Also did returning `""` instead of `null` help?

**Comment by pmouawad** [comment]
Hello @weisJ ,
Is there a way to get a CI build of darklaf ?
Or do I need to build it myself ?
Thanks

**Comment by weisJ** [comment]
You can use the nightly snapshot builds.
````kotlin
repositories {
    maven {
        url = uri("https://oss.sonatype.org/content/repositories/snapshots/")
    }
}

configurations.all {
    resolutionStrategy.cacheChangingModulesFor(0, "seconds")
}

dependencies {
    implementation("com.github.weisj:darklaf-core:latest.integration")
}
````

**Comment by pmouawad** [comment]
Hello,
Sorry for late reply.
I tried latest integration and I don't reproduce issue.
Thanks

**Comment by pmouawad** [comment]
Hello,
I tried last integration and issue is still there.

Try entering ${varName} in duration field, it is not possible.

Regards
