### ISSUE TITLE
In last version 2.23 using GroupLayout leads to NPE: null at javax.swing.plaf.basic.BasicTextFieldUI.getBaseline(BasicTextFieldUI.java:126) ~[?:1.8.0_201]

### ISSUE THREAD

**Issue by pmouawad** [weisJ/darklaf#184]
Describe the bug
Steps to reproduce:

Download JMeter nightly, replace Darklaf by last version, extract it.
Open the Jmeter and set the look and feel to Darklaf-IntelliJ
Open a Test Element that uses GroupLayout with createParallelGroup
When you go on Element, it does not display and you get tons of Stacktraces like below

Screenshots
<img width="1435" alt="Screen Shot 2020-06-13 at 18 40 42" src="https://user-images.githubusercontent.com/3127467/84574233-6988bf00-ada5-11ea-9c6a-c35df9ce582e.png">

See attached screenshot showing blank GUI.

Additional Information:

Java.version=1.8.0_201
java.vm.name=Java HotSpot(TM) 64-Bit Server VM
os.name=Mac OS X
os.arch=x86_64
os.version=10.11.6

Darklaf Version: 2.2.3

**It does not happen with JMeter 5.3/ Darklaf 2.1.1**

Additional context
Using JMeter nightly build updated with 2.2.3

Exception:

`2020-06-13 18:35:33,696 ERROR o.a.j.JMeter: Uncaught exception in thread Thread[AWT-EventQueue-0,6,main]
java.lang.NullPointerException: null
	at javax.swing.plaf.basic.BasicTextFieldUI.getBaseline(BasicTextFieldUI.java:126) ~[?:1.8.0_201]
	at com.github.weisj.darklaf.ui.text.bridge.DarkTextFieldUIBridge.getBaseline(DarkTextFieldUIBridge.java:58) ~[darklaf-core-2.2.3.jar:2.2.3]
	at javax.swing.JComponent.getBaseline(JComponent.java:2564) ~[?:1.8.0_201]
	at javax.swing.GroupLayout$ComponentSpring.getBaseline(GroupLayout.java:3075) ~[?:1.8.0_201]
	at javax.swing.GroupLayout$BaselineGroup.calculateBaselineAndResizeBehavior(GroupLayout.java:2732) ~[?:1.8.0_201]
	at javax.swing.GroupLayout$BaselineGroup.calculateSize(GroupLayout.java:2708) ~[?:1.8.0_201]
	at javax.swing.GroupLayout$Group.calculateMinimumSize(GroupLayout.java:1598) ~[?:1.8.0_201]
	at javax.swing.GroupLayout$ParallelGroup.calculateMinimumSize(GroupLayout.java:2569) ~[?:1.8.0_201]
	at javax.swing.GroupLayout$Spring.getMinimumSize(GroupLayout.java:1336) ~[?:1.8.0_201]
	at javax.swing.GroupLayout$Group.getSpringSize(GroupLayout.java:1636) ~[?:1.8.0_201]
	at javax.swing.GroupLayout$Group.calculateSize(GroupLayout.java:1624) ~[?:1.8.0_201]
	at javax.swing.GroupLayout$Group.calculateMinimumSize(GroupLayout.java:1598) ~[?:1.8.0_201]
	at javax.swing.GroupLayout$Spring.getMinimumSize(GroupLayout.java:1336) ~[?:1.8.0_201]
	at javax.swing.GroupLayout$Group.getSpringSize(GroupLayout.java:1636) ~[?:1.8.0_201]
	at javax.swing.GroupLayout$Group.calculateSize(GroupLayout.java:1622) ~[?:1.8.0_201]
	at javax.swing.GroupLayout$Group.calculateMinimumSize(GroupLayout.java:1598) ~[?:1.8.0_201]
	at javax.swing.GroupLayout$ParallelGroup.calculateMinimumSize(GroupLayout.java:2569) ~[?:1.8.0_201]
	at javax.swing.GroupLayout$Spring.getMinimumSize(GroupLayout.java:1336) ~[?:1.8.0_201]
	at javax.swing.GroupLayout$Group.getSpringSize(GroupLayout.java:1636) ~[?:1.8.0_201]
	at javax.swing.GroupLayout$Group.calculateSize(GroupLayout.java:1622) ~[?:1.8.0_201]
	at javax.swing.GroupLayout$Group.calculateMinimumSize(GroupLayout.java:1598) ~[?:1.8.0_201]
	at javax.swing.GroupLayout$Spring.getMinimumSize(GroupLayout.java:1336) ~[?:1.8.0_201]
	at javax.swing.GroupLayout.calculateAutopadding(GroupLayout.java:1068) ~[?:1.8.0_201]
	at javax.swing.GroupLayout.prepare(GroupLayout.java:1059) ~[?:1.8.0_201]
	at javax.swing.GroupLayout.minimumLayoutSize(GroupLayout.java:896) ~[?:1.8.0_201]
	at java.awt.Container.minimumSize(Container.java:1851) ~[?:1.8.0_201]
	at java.awt.Container.getMinimumSize(Container.java:1835) ~[?:1.8.0_201]
	at javax.swing.JComponent.getMinimumSize(JComponent.java:1746) ~[?:1.8.0_201]
	at javax.swing.GroupLayout$ComponentSpring.calculateNonlinkedMinimumSize(GroupLayout.java:3008) ~[?:1.8.0_201]
	at javax.swing.GroupLayout$ComponentSpring.calculateMinimumSize(GroupLayout.java:2972) ~[?:1.8.0_201]
	at javax.swing.GroupLayout$Spring.getMinimumSize(GroupLayout.java:1336) ~[?:1.8.0_201]
	at javax.swing.GroupLayout$ComponentSpring.calculatePreferredSize(GroupLayout.java:2979) ~[?:1.8.0_201]
	at javax.swing.GroupLayout$Spring.getPreferredSize(GroupLayout.java:1346) ~[?:1.8.0_201]
	at javax.swing.GroupLayout$Group.getSpringSize(GroupLayout.java:1638) ~[?:1.8.0_201]
	at javax.swing.GroupLayout$Group.calculateSize(GroupLayout.java:1624) ~[?:1.8.0_201]
	at javax.swing.GroupLayout$Group.calculatePreferredSize(GroupLayout.java:1602) ~[?:1.8.0_201]
	at javax.swing.GroupLayout$Spring.getPreferredSize(GroupLayout.java:1346) ~[?:1.8.0_201]
	at javax.swing.GroupLayout$Group.getSpringSize(GroupLayout.java:1638) ~[?:1.8.0_201]
	at javax.swing.GroupLayout$Group.calculateSize(GroupLayout.java:1625) ~[?:1.8.0_201]
	at javax.swing.GroupLayout$Group.calculatePreferredSize(GroupLayout.java:1602) ~[?:1.8.0_201]
	at javax.swing.GroupLayout$Spring.getPreferredSize(GroupLayout.java:1346) ~[?:1.8.0_201]
	at javax.swing.GroupLayout$Group.getSpringSize(GroupLayout.java:1638) ~[?:1.8.0_201]
	at javax.swing.GroupLayout$Group.calculateSize(GroupLayout.java:1622) ~[?:1.8.0_201]
	at javax.swing.GroupLayout$Group.calculatePreferredSize(GroupLayout.java:1602) ~[?:1.8.0_201]
	at javax.swing.GroupLayout$Spring.getPreferredSize(GroupLayout.java:1346) ~[?:1.8.0_201]
	at javax.swing.GroupLayout$Group.getSpringSize(GroupLayout.java:1638) ~[?:1.8.0_201]
	at javax.swing.GroupLayout$Group.calculateSize(GroupLayout.java:1622) ~[?:1.8.0_201]
	at javax.swing.GroupLayout$Group.calculatePreferredSize(GroupLayout.java:1602) ~[?:1.8.0_201]
	at javax.swing.GroupLayout$Spring.getPreferredSize(GroupLayout.java:1346) ~[?:1.8.0_201]
	at javax.swing.GroupLayout.calculateAutopadding(GroupLayout.java:1071) ~[?:1.8.0_201]
	at javax.swing.GroupLayout.prepare(GroupLayout.java:1058) ~[?:1.8.0_201]
	at javax.swing.GroupLayout.preferredLayoutSize(GroupLayout.java:878) ~[?:1.8.0_201]
	at java.awt.Container.preferredSize(Container.java:1799) ~[?:1.8.0_201]
	at java.awt.Container.getPreferredSize(Container.java:1783) ~[?:1.8.0_201]
	at javax.swing.JComponent.getPreferredSize(JComponent.java:1664) ~[?:1.8.0_201]
	at javax.swing.ScrollPaneLayout.layoutContainer(ScrollPaneLayout.java:791) ~[?:1.8.0_201]
	at com.github.weisj.darklaf.delegate.ScrollLayoutManagerDelegate.layoutContainer(ScrollLayoutManagerDelegate.java:125) ~[darklaf-core-2.2.3.jar:2.2.3]
	at com.github.weisj.darklaf.ui.scrollpane.DarkScrollPaneUI$1.layoutContainer(DarkScrollPaneUI.java:142) ~[darklaf-core-2.2.3.jar:2.2.3]
	at java.awt.Container.layout(Container.java:1513) ~[?:1.8.0_201]
	at java.awt.Container.doLayout(Container.java:1502) ~[?:1.8.0_201]
	at java.awt.Container.validateTree(Container.java:1698) ~[?:1.8.0_201]
	at java.awt.Container.validateTree(Container.java:1707) ~[?:1.8.0_201]
	at java.awt.Container.validateTree(Container.java:1707) ~[?:1.8.0_201]
	at java.awt.Container.validateTree(Container.java:1707) ~[?:1.8.0_201]
	at java.awt.Container.validateTree(Container.java:1707) ~[?:1.8.0_201]
	at java.awt.Container.validateTree(Container.java:1707) ~[?:1.8.0_201]
	at java.awt.Container.validateTree(Container.java:1707) ~[?:1.8.0_201]
	at java.awt.Container.validate(Container.java:1633) ~[?:1.8.0_201]
	at javax.swing.RepaintManager$3.run(RepaintManager.java:711) ~[?:1.8.0_201]
	at javax.swing.RepaintManager$3.run(RepaintManager.java:709) ~[?:1.8.0_201]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_201]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74) ~[?:1.8.0_201]
	at javax.swing.RepaintManager.validateInvalidComponents(RepaintManager.java:708) ~[?:1.8.0_201]
	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1731) ~[?:1.8.0_201]
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311) ~[?:1.8.0_201]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758) ~[?:1.8.0_201]
	at java.awt.EventQueue.access$500(EventQueue.java:97) ~[?:1.8.0_201]
	at java.awt.EventQueue$3.run(EventQueue.java:709) ~[?:1.8.0_201]
	at java.awt.EventQueue$3.run(EventQueue.java:703) ~[?:1.8.0_201]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_201]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74) ~[?:1.8.0_201]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728) ~[?:1.8.0_201]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205) [?:1.8.0_201]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [?:1.8.0_201]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [?:1.8.0_201]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:1.8.0_201]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [?:1.8.0_201]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [?:1.8.0_201`

**Comment by pmouawad** [comment]
@weisJ , issue has been introduced by 2.2.0
