### ISSUE TITLE
java.lang.UnsupportedOperationException: TRANSLUCENT translucency is not supported.  

### ISSUE THREAD

**Issue by pmouawad** [weisJ/darklaf#197]
**Describe the bug**
Hello @weisJ , we have this bug report:

- https://bz.apache.org/bugzilla/show_bug.cgi?id=64630

**To Reproduce**

- https://bz.apache.org/bugzilla/show_bug.cgi?id=64630

**Stacktrace**

`
java.lang.UnsupportedOperationException: TRANSLUCENT translucency is not supported.
        at java.awt.Window.setOpacity(Window.java:3625) ~[?:1.8.0_121]
        at com.github.weisj.darklaf.ui.tooltip.DarkTooltipUI$FadeInAnimator.paintNow(DarkTooltipUI.java:346) ~[darklaf-core-2.1.1.jar:2.1.1]
        at com.github.weisj.darklaf.graphics.Animator.paint(Animator.java:140) ~[darklaf-core-2.1.1.jar:2.1.1]
        at com.github.weisj.darklaf.graphics.Animator.onTick(Animator.java:176) ~[darklaf-core-2.1.1.jar:2.1.1]
        at com.github.weisj.darklaf.graphics.Animator.access$000(Animator.java:38) ~[darklaf-core-2.1.1.jar:2.1.1]
        at com.github.weisj.darklaf.graphics.Animator$1.lambda$run$0(Animator.java:130) ~[darklaf-core-2.1.1.jar:2.1.1]
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311) ~[?:1.8.0_121]
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756) ~[?:1.8.0_121]
        at java.awt.EventQueue.access$500(EventQueue.java:97) ~[?:1.8.0_121]
        at java.awt.EventQueue$3.run(EventQueue.java:709) ~[?:1.8.0_121]
        at java.awt.EventQueue$3.run(EventQueue.java:703) ~[?:1.8.0_121]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_121]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80) ~[?:1.8.0_121]
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:726) ~[?:1.8.0_121]
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) [?:1.8.0_121]
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [?:1.8.0_121]
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [?:1.8.0_121]
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:1.8.0_121]
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [?:1.8.0_121]
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [?:1.8.0_121]
2020-07-28 13:40:46,862 ERROR o.a.j.JMeter: Uncaught exception in thread Thread[AWT-EventQueue-0,6,main]
java.lang.UnsupportedOperationException: TRANSLUCENT translucency is not supported.
        at java.awt.Window.setOpacity(Window.java:3625) ~[?:1.8.0_121]
        at com.github.weisj.darklaf.ui.tooltip.DarkTooltipUI$FadeInAnimator.paintNow(DarkTooltipUI.java:346) ~[darklaf-core-2.1.1.jar:2.1.1]
        at com.github.weisj.darklaf.graphics.Animator.paint(Animator.java:140) ~[darklaf-core-2.1.1.jar:2.1.1]
        at com.github.weisj.darklaf.graphics.Animator.onTick(Animator.java:176) ~[darklaf-core-2.1.1.jar:2.1.1]
        at com.github.weisj.darklaf.graphics.Animator.access$000(Animator.java:38) ~[darklaf-core-2.1.1.jar:2.1.1]
        at com.github.weisj.darklaf.graphics.Animator$1.lambda$run$0(Animator.java:130) ~[darklaf-core-2.1.1.jar:2.1.1]
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311) ~[?:1.8.0_121]
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756) ~[?:1.8.0_121]
        at java.awt.EventQueue.access$500(EventQueue.java:97) ~[?:1.8.0_121]
        at java.awt.EventQueue$3.run(EventQueue.java:709) ~[?:1.8.0_121]
        at java.awt.EventQueue$3.run(EventQueue.java:703) ~[?:1.8.0_121]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_121]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80) ~[?:1.8.0_121]
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:726) ~[?:1.8.0_121]
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) [?:1.8.0_121]
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [?:1.8.0_121]
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [?:1.8.0_121]
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:1.8.0_121]
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [?:1.8.0_121]
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [?:1.8.0_121]
`

**Additional Information:**
 - OS: Linux
 - OS Version: don'tknow
- Darklaf Version: 2.1.1

**Comment by weisJ** [comment]
Hi, this has been reported before (https://github.com/weisJ/darklaf/issues/174) and was fixed in version `2.2.1` (0faa6eeee83c4521550d3e3cb9949730096f1945)

**Comment by pmouawad** [comment]
Thanks !
