### ISSUE TITLE
NullPointerException at javax.swing.ToolTipManager.initiateToolTip

### ISSUE THREAD

**Issue by pmouawad** [weisJ/darklaf#207]
**Describe the bug**

Getting stacktrace in logs

````
2020-09-15 09:40:28,430 ERROR o.a.j.JMeter: Uncaught exception in thread Thread[AWT-EventQueue-0,6,main]
java.lang.NullPointerException: null
at javax.swing.ToolTipManager.initiateToolTip(ToolTipManager.java:478) ~[?:1.8.0_212]
at javax.swing.ToolTipManager.mouseEntered(ToolTipManager.java:435) ~[?:1.8.0_212]
at java.awt.AWTEventMulticaster.mouseEntered(AWTEventMulticaster.java:300) ~[?:1.8.0_212]
at java.awt.AWTEventMulticaster.mouseEntered(AWTEventMulticaster.java:299) ~[?:1.8.0_212]
at java.awt.AWTEventMulticaster.mouseEntered(AWTEventMulticaster.java:299) ~[?:1.8.0_212]
at java.awt.AWTEventMulticaster.mouseEntered(AWTEventMulticaster.java:299) ~[?:1.8.0_212]
at java.awt.AWTEventMulticaster.mouseEntered(AWTEventMulticaster.java:299) ~[?:1.8.0_212]
at java.awt.AWTEventMulticaster.mouseEntered(AWTEventMulticaster.java:299) ~[?:1.8.0_212]
at java.awt.AWTEventMulticaster.mouseEntered(AWTEventMulticaster.java:299) ~[?:1.8.0_212]
at java.awt.AWTEventMulticaster.mouseEntered(AWTEventMulticaster.java:299) ~[?:1.8.0_212]
at java.awt.AWTEventMulticaster.mouseEntered(AWTEventMulticaster.java:299) ~[?:1.8.0_212]
at java.awt.AWTEventMulticaster.mouseEntered(AWTEventMulticaster.java:299) ~[?:1.8.0_212]
at java.awt.Component.processMouseEvent(Component.java:6548) ~[?:1.8.0_212]
at javax.swing.JComponent.processMouseEvent(JComponent.java:3324) ~[?:1.8.0_212]
at java.awt.Component.processEvent(Component.java:6304) ~[?:1.8.0_212]
at java.awt.Container.processEvent(Container.java:2239) ~[?:1.8.0_212]
at java.awt.Component.dispatchEventImpl(Component.java:4889) ~[?:1.8.0_212]
at java.awt.Container.dispatchEventImpl(Container.java:2297) ~[?:1.8.0_212]
at java.awt.Component.dispatchEvent(Component.java:4711) ~[?:1.8.0_212]
at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904) ~[?:1.8.0_212]
at java.awt.LightweightDispatcher.retargetMouseEnterExit(Container.java:4686) ~[?:1.8.0_212]
at java.awt.LightweightDispatcher.trackMouseEnterExit(Container.java:4664) ~[?:1.8.0_212]
at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4515) ~[?:1.8.0_212]
at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476) ~[?:1.8.0_212]
at java.awt.Container.dispatchEventImpl(Container.java:2283) ~[?:1.8.0_212]
at java.awt.Window.dispatchEventImpl(Window.java:2746) ~[?:1.8.0_212]
at java.awt.Component.dispatchEvent(Component.java:4711) ~[?:1.8.0_212]
at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760) ~[?:1.8.0_212]
at java.awt.EventQueue.access$500(EventQueue.java:97) ~[?:1.8.0_212]
at java.awt.EventQueue$3.run(EventQueue.java:709) ~[?:1.8.0_212]
at java.awt.EventQueue$3.run(EventQueue.java:703) ~[?:1.8.0_212]
at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_212]
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74) ~[?:1.8.0_212]
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84) ~[?:1.8.0_212]
at java.awt.EventQueue$4.run(EventQueue.java:733) ~[?:1.8.0_212]
at java.awt.EventQueue$4.run(EventQueue.java:731) ~[?:1.8.0_212]
at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_212]
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74) ~[?:1.8.0_212]
at java.awt.EventQueue.dispatchEvent(EventQueue.java:730) ~[?:1.8.0_212]
at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205) [?:1.8.0_212]
at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [?:1.8.0_212]
at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [?:1.8.0_212]
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:1.8.0_212]
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [?:1.8.0_212]
at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [?:1.8.0_212]

````
**To Reproduce**

No reproducer

**Screenshots**

No visible impact

**Additional Information:**
 - OS: macOS & Windows
 - OS Version: Windows 10
   - For issues with frame decorations on Windows please provide the explicit [Windows build number](https://docs.microsoft.com/en-gb/windows/release-information/).
- Darklaf Version: latest.integration and latest version

**Comment by weisJ** [comment]
Hi @pmouawa,
is this related to #183?

**Comment by pmouawad** [comment]
Hi @weisJ ,
The #183 was supposed to be fixed.
This one  is happening in latest version of Darklaf.

Thanks

**Comment by weisJ** [comment]
Which component of JMeter is affected? From the stacktrace alone I can't make out what is causing the tooltip text to be null.

**Comment by weisJ** [comment]
@pmouawad did https://github.com/apache/jmeter/pull/621 solve the issue for you?

**Comment by pmouawad** [comment]
Hello @weisJ ,
Yes it solved it.
Thanks
