### ISSUE TITLE
java.lang.NullPointerException: null at com.github.weisj.darklaf.ui.scrollpane.DarkScrollPaneUI.viewportStateChanged

### ISSUE THREAD

**Issue by pmouawad** [weisJ/darklaf#210]
**Describe the bug**
Trying to upgrade jmeter to 2.4.9.
I get a stacktrace on startup:

`2020-09-23 21:18:23,798 ERROR o.a.j.JMeter: Uncaught exception in thread Thread[AWT-EventQueue-0,6,main]
java.lang.NullPointerException: null
        at com.github.weisj.darklaf.ui.scrollpane.DarkScrollPaneUI.viewportStateChanged(DarkScrollPaneUI.java:166) ~[darklaf-core-2.4.9.jar:2.4.9]
        at javax.swing.JViewport.fireStateChanged(JViewport.java:1369) ~[?:1.8.0_201]
        at javax.swing.JViewport.reshape(JViewport.java:839) ~[?:1.8.0_201]
        at java.awt.Component.setBounds(Component.java:2261) ~[?:1.8.0_201]
        at java.awt.Component.setBounds(Component.java:2405) ~[?:1.8.0_201]
        at javax.swing.ScrollPaneLayout.layoutContainer(ScrollPaneLayout.java:890) ~[?:1.8.0_201]
        at com.github.weisj.darklaf.delegate.ScrollLayoutManagerDelegate.layoutContainer(ScrollLayoutManagerDelegate.java:120) ~[darklaf-core-2.4.9.jar:2.4.9]
        at com.github.weisj.darklaf.ui.scrollpane.DarkScrollPaneUI$1.layoutContainer(DarkScrollPaneUI.java:197) ~[darklaf-core-2.4.9.jar:2.4.9]
        at java.awt.Container.layout(Container.java:1513) ~[?:1.8.0_201]
        at java.awt.Container.doLayout(Container.java:1502) ~[?:1.8.0_201]
        at java.awt.Container.validateTree(Container.java:1698) ~[?:1.8.0_201]
        at java.awt.Container.validate(Container.java:1633) ~[?:1.8.0_201]
        at javax.swing.RepaintManager$3.run(RepaintManager.java:711) ~[?:1.8.0_201]
        at javax.swing.RepaintManager$3.run(RepaintManager.java:709) ~[?:1.8.0_201]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_201]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74) ~[?:1.8.0_201]
        at javax.swing.RepaintManager.validateInvalidComponents(RepaintManager.java:708) ~[?:1.8.0_201]
        at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1731) ~[?:1.8.0_201]
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311) ~[?:1.8.0_201]
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758) ~[?:1.8.0_201]
        at java.awt.EventQueue.access$500(EventQueue.java:97) ~[?:1.8.0_201]
        at java.awt.EventQueue$3.run(EventQueue.java:709) ~[?:1.8.0_201]
        at java.awt.EventQueue$3.run(EventQueue.java:703) ~[?:1.8.0_201]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_201]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74) ~[?:1.8.0_201]
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:728) ~[?:1.8.0_201]
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205) [?:1.8.0_201]
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [?:1.8.0_201]
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [?:1.8.0_201]
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:1.8.0_201]
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [?:1.8.0_201]
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [?:1.8.0_201]
`

**To Reproduce**
Get jmeter from github
update in gradle.properties Darklaf to 2.4.9

run 
`
gradlew runGui
`

**Screenshots**
If applicable, add screenshots to help explain your problem. Visual material should only be used in assistance
to the description of the Bug and **does not** replace it.

**Additional Information:**
 - OS: macOS
 - OS Version: 10.11.6
- Darklaf 2.4.9

**Comment by weisJ** [comment]
Hi @pmouawad 
the problem should be gone now. Can you confirm this? If so I'll relase `2.4.10` with the fix ASAP.

**Comment by pmouawad** [comment]
Hello @weisJ ,
Is there a latest.integration available ? 

Thanks

**Comment by pmouawad** [comment]
Related commit:

https://github.com/weisJ/darklaf/commit/83edf1580eb7217fb51844a9a01ac384d4302f28

**Comment by weisJ** [comment]
There should be one available. It might take a bit though until it's available.

**Comment by pmouawad** [comment]
Hello @weisJ ,
Issue seems to be fixed.
Thanks

**Comment by pmouawad** [comment]
Hello @weisJ ,
When do you plan a release ?

Thanks

**Comment by weisJ** [comment]
I'll release the next version this evening.
