### ISSUE TITLE
NotSerializableException when dragging JTabFrame tab

### ISSUE THREAD

**Issue by GraxCode** [weisJ/darklaf#236]
**Describe the bug**
```
java.io.NotSerializableException: com.github.weisj.darklaf.ui.tabframe.TabFrameTransferHandler$TabTransferable$TabTransferData
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1193)
	at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:353)
	at java.desktop/sun.awt.datatransfer.DataTransferer.convertObjectToBytes(DataTransferer.java:979)
	at java.desktop/sun.awt.datatransfer.DataTransferer.translateTransferable(DataTransferer.java:964)
	at java.desktop/sun.awt.datatransfer.DataTransferer$2.run(DataTransferer.java:1880)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```
**To Reproduce**
Happens when dragging a JTabFrame tab to another location.

**Additional Information:**
 - OS: Manjaro
- Darklaf Version: 2.6.1

**Comment by weisJ** [comment]
Is this within a single application or between different applications? Otherwise I'm not sure why serializing the 'TabTransferData' is even attempted.

**Comment by GraxCode** [comment]
I don't know, but i assume it is not within a single one.

**Comment by GraxCode** [comment]
It seems like this happens when dragging the tab outside of the frame onto the desktop. I am on Manjaro KDE.

**Comment by weisJ** [comment]
Thanks for the info. I'll investigate how to rule out the desktop as a drop target then. It really doesn't make much sense to drop a UI component on the desktop :D.
