### ISSUE TITLE
NPE in JInternalFrame

### ISSUE THREAD

**Issue by ThexXTURBOXx** [weisJ/darklaf#239]
**Describe the bug**
#179 is here again. A `NullPointerException` when calling `setTitle` in `JInternalFrame`

**To Reproduce**
Call `setTitle` within `JInternalFrame`

**Additional Information:**
 - OS: Windows 10
 - OS Version: 19043.1055 (21H1)
- Darklaf Version: 2.6.0 and 2.6.1

**Additional context**
```
java.lang.NullPointerException
	at sun.font.FontDesignMetrics$MetricsKey.init(FontDesignMetrics.java:217)
	at sun.font.FontDesignMetrics.getMetrics(FontDesignMetrics.java:286)
	at sun.swing.SwingUtilities2.getFontMetrics(SwingUtilities2.java:1124)
	at javax.swing.JComponent.getFontMetrics(JComponent.java:1626)
	at com.github.weisj.darklaf.ui.internalframe.DarkInternalFrameTitlePane$DarkTitlePaneLayout.minimumLayoutSize(DarkInternalFrameTitlePane.java:310)
	at java.awt.Container.minimumSize(Container.java:1851)
	at java.awt.Container.getMinimumSize(Container.java:1835)
	at javax.swing.JComponent.getMinimumSize(JComponent.java:1746)
	at javax.swing.plaf.basic.BasicInternalFrameUI$Handler.minimumLayoutSize(BasicInternalFrameUI.java:1319)
	at javax.swing.plaf.basic.BasicInternalFrameUI.getMinimumSize(BasicInternalFrameUI.java:342)
	at javax.swing.JComponent.getMinimumSize(JComponent.java:1744)
	at javax.swing.plaf.basic.BasicInternalFrameUI$Handler.propertyChange(BasicInternalFrameUI.java:1449)
	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
	at java.awt.Component.firePropertyChange(Component.java:8434)
	at javax.swing.JInternalFrame.setTitle(JInternalFrame.java:1051)
	at the.bytecode.club.bytecodeviewer.gui.WorkPane.<init>(WorkPane.java:65)
	at the.bytecode.club.bytecodeviewer.gui.MainViewerGUI.<init>(MainViewerGUI.java:83)
	at the.bytecode.club.bytecodeviewer.BytecodeViewer.main(BytecodeViewer.java:214)
```

**Comment by weisJ** [comment]
Thank you for reporting! It seems like the `JInternalFrame` hasn't any font set causing `#getFontMetrics` to fail as the passed font is `null`. Could you please verify that manually setting a font for the internal frame solves the issue?

**Comment by ThexXTURBOXx** [comment]
Snapshot and setting the font manually works! Thank you very much :)
