### ISSUE TITLE
NPE in DarkTreeExpansionAnimationListener

### ISSUE THREAD

**Issue by FSchumacher** [weisJ/darklaf#275]
**Describe the bug**
A NPE is thrown in DarkTreeExpansionAnimationListener$TreeStateAnimator.repaint

**To Reproduce**
A JMeter user posted in https://bz.apache.org/bugzilla/show_bug.cgi?id=65579 a description to reproduce, which I couldn't reproduce on my setup. But I believe it is due to an animation done on a tree that gets emptied while the animation happens.

**Additional Information:**
```
2021-09-17 21:34:36,173 ERROR o.a.j.JMeter: Uncaught exception in thread Thread[AWT-EventQueue-0,6,main]
java.lang.NullPointerException: null
	at com.github.weisj.darklaf.ui.tree.DarkTreeExpansionAnimationListener$TreeStateAnimator.repaint(DarkTreeExpansionAnimationListener.java:93) ~[darklaf-core-2.7.2.jar:2.7.2]
	at com.github.weisj.darklaf.ui.tree.DarkTreeExpansionAnimationListener$TreeStateAnimator.paintCycleEnd(DarkTreeExpansionAnimationListener.java:109) ~[darklaf-core-2.7.2.jar:2.7.2]
	at java.awt.event.InvocationEvent.dispatch(Unknown Source) ~[?:1.8.0_131]
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source) ~[?:1.8.0_131]
	at java.awt.EventQueue.access$500(Unknown Source) ~[?:1.8.0_131]
	at java.awt.EventQueue$3.run(Unknown Source) ~[?:1.8.0_131]
	at java.awt.EventQueue$3.run(Unknown Source) ~[?:1.8.0_131]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_131]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) ~[?:1.8.0_131]
	at java.awt.EventQueue.dispatchEvent(Unknown Source) ~[?:1.8.0_131]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source) [?:1.8.0_131]
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source) [?:1.8.0_131]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source) [?:1.8.0_131]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:1.8.0_131]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:1.8.0_131]
	at java.awt.EventDispatchThread.run(Unknown Source) [?:1.8.0_131]
```
- OS: Version Windows 10 Home Chinese Version, Version number 21H1, Operating system internal version 19043.1165
- Darklaf Version: 2.7.2

**Additional context**
None known

**Comment by weisJ** [comment]
The fix for this issue and #274 are available in version 2.7.3
