### ISSUE TITLE
java.lang.NoClassDefFoundError: com/github/weisj/darklaf/platform/decorations/DecorationsProvider

### ISSUE THREAD

**Issue by hpdrago** [weisJ/darklaf#290]
**Describe the bug**
Hello, I used the 2.72 maven target through Ivy:

<dependency org="com.github.weisj"         name="darklaf-core"         rev="2.7.2"          force="true" conf="compile->compile(*),master(*);runtime->runtime(*)" transitive="true"/>

The follwoing
darklaf-core-2.7.2.jar
darklaf-property-loader-2.7.2.jar
darklaf-theme-2.7.2.jar
darklaf-utils-2.7.2.jar

And I get the runtime error:

java.lang.NoClassDefFoundError: com/github/weisj/darklaf/platform/decorations/DecorationsProvider
	at com.github.weisj.darklaf.DarkLaf.setupDecorations(DarkLaf.java:131) ~[darklaf-core-2.7.2.jar:2.7.2]
	at com.github.weisj.darklaf.DarkLaf.initialize(DarkLaf.java:123) ~[darklaf-core-2.7.2.jar:2.7.2]
	at javax.swing.UIManager.setLookAndFeel(UIManager.java:586) ~[?:?]
	at com.github.weisj.darklaf.LafInstaller.install(LafInstaller.java:48) ~[darklaf-core-2.7.2.jar:2.7.2]
	at com.github.weisj.darklaf.LafManager.install(LafManager.java:438) ~[darklaf-core-2.7.2.jar:2.7.2]
	at com.awi.flexids.common.LookAndFeelManager.setDarkMode(LookAndFeelManager.java:88) ~[FlexIDS.jar:?]
	at com.awi.flexids.flexmon.FlexMonGUI.initComponents(FlexMonGUI.java:220) ~[FlexIDS.jar:?]
	at com.awi.flexids.flexmon.FlexMonGUI.<init>(FlexMonGUI.java:144) ~[FlexIDS.jar:?]
	at com.awi.flexids.flexmon.FlexMonManager.startUp(FlexMonManager.java:107) ~[FlexIDS.jar:?]
	at com.awi.flexids.server.ServerManager.startFlexMon(ServerManager.java:501) ~[FlexIDS.jar:?]
	at com.awi.flexids.server.controller.ServerControllerServer.processSynchronized(ServerControllerServer.java:166) ~[FlexIDS.jar:?]
	at com.awi.flexids.server.controller.ServerControllerServer.process(ServerControllerServer.java:137) ~[FlexIDS.jar:?]
	at com.awi.flexids.server.SocketObjectServer.process(SocketObjectServer.java:186) ~[FlexIDS.jar:?]
	at com.awi.flexids.server.SocketObjectServer.process(SocketObjectServer.java:133) ~[FlexIDS.jar:?]
	at com.awi.flexids.server.controller.ServerControllerServer.process(ServerControllerServer.java:84) ~[FlexIDS.jar:?]
	at com.awi.flexids.server.SocketServer$RequestRunnable.run(SocketServer.java:248) ~[FlexIDS.jar:?]
	at com.awi.threadpool.RunnableTask.run(RunnableTask.java:67) [awicommon-3.2.3.jar:3.2.3]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassNotFoundException: com.github.weisj.darklaf.platform.decorations.DecorationsProvider
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581) ~[?:?]
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
	... 20 more

**To Reproduce**

**Screenshots**
See stack trace

**Additional Information:**
 - OS: Windows
 - OS Version: 10
   - For issues with frame decorations on Windows please provide the explicit [Windows build number](https://docs.microsoft.com/en-gb/windows/release-information/).
- Darklaf Version: 2.7.2
  - **Note**: If you are using the `latest.integration` version please try to replicate the issue with the latest stable release.

**Additional context**

**Comment by hpdrago** [comment]
solved dependencies.
