### ISSUE TITLE
SAXException with Icons

### ISSUE THREAD

**Issue by GraxCode** [weisJ/darklaf#320]
**Describe the bug**
I got this exception randomly while rendering a JTree. It only happened once, and I don't know how to reproduce it. Maybe has to do with missing synchronization.

````
WARNUNG: Could not load SVG 
org.xml.sax.SAXException: FWK005 parse may not be called while parsing.
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1266)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:635)
	at com.github.weisj.jsvg.parser.SVGLoader.load(SVGLoader.java:136)
	at com.github.weisj.jsvg.parser.SVGLoader.load(SVGLoader.java:116)
	at com.github.weisj.darklaf.properties.icons.DarkSVGIcon$SVGDocumentHolder.ensureLoaded(DarkSVGIcon.java:335)
	at com.github.weisj.darklaf.properties.icons.DarkSVGIcon$SVGDocumentHolder.svgDocument(DarkSVGIcon.java:347)
	at com.github.weisj.darklaf.properties.icons.DarkSVGIcon$SVGDocumentHolder.access$300(DarkSVGIcon.java:315)
	at com.github.weisj.darklaf.properties.icons.DarkSVGIcon.getSVGDocument(DarkSVGIcon.java:285)
	at com.github.weisj.darklaf.properties.icons.DarkSVGIcon.ensureSizeLoaded(DarkSVGIcon.java:254)
	at com.github.weisj.darklaf.properties.icons.DarkSVGIcon.getIconWidth(DarkSVGIcon.java:238)
	at java.desktop/javax.swing.JLabel.setIcon(JLabel.java:396)
````

**To Reproduce**
I don't know how to.

**Additional Information:**
- Darklaf Version: 3.0.0

**Comment by weisJ** [comment]
Is there more to this stacktrace? Theoretically this shouldn’t be able to happen as long as all operations are confined to the swing thread (nonetheless I’ll try to make this more robust)

**Comment by weisJ** [comment]
Should be fixed with the latest snapshot. I'll release a fix version if this works for you :)

**Comment by GraxCode** [comment]
It's not that urgent. Release it with the next version ;)

**Comment by weisJ** [comment]
Version 3.0.1 has been released and should fix it.
