### ISSUE TITLE
Demo crashes

### ISSUE THREAD

**Issue by kirill-grouchnikov** [weisJ/darklaf#49]
1. Download the ZIP from https://github.com/weisJ/darklaf/archive/master.zip
2. Open it locally
3. Open build.gradle.kts in IntelliJ and choose to open as project
4. Wait until the project is loaded and built
5. Right click on DarklafDemo and choose to Run

```
[2020-02-18 11:38:21] [SEVERE] java.lang.NullPointerException: inStream parameter is null [at com.github.weisj.darklaf.DarkLaf]
                     [Details] java.base/java.util.Objects.requireNonNull(Objects.java:246),
                               java.base/java.util.Properties.load(Properties.java:403),
                               com.github.weisj.darklaf.util.PropertyLoader.loadProperties(PropertyLoader.java:78),
                               com.github.weisj.darklaf.theme.Theme.loadDecorationProperties(Theme.java:149),
                               com.github.weisj.darklaf.DarkLaf.loadThemeDefaults(DarkLaf.java:170),
                               com.github.weisj.darklaf.DarkLaf.getDefaults(DarkLaf.java:88),
                               java.desktop/javax.swing.UIManager.setLookAndFeel(UIManager.java:587),
                               java.desktop/javax.swing.UIManager.setLookAndFeel(UIManager.java:633),
                               com.github.weisj.darklaf.LafManager.install(LafManager.java:166),
                               DarklafDemo.lambda$main$0(DarklafDemo.java:9),
                               java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313),
                               java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770),
                               java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721),
                               java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715),
                               java.base/java.security.AccessController.doPrivileged(AccessController.java:389),
                               java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85),
                               java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740),
                               java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203),
                               java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124),
                               java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113),
                               java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109),
                               java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101),
                               java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at com.github.weisj.darklaf.ui.button.DarkButtonBorder.getBorderInsets(DarkButtonBorder.java:178)
	at java.desktop/javax.swing.JComponent.getInsets(JComponent.java:1840)
	at java.desktop/javax.swing.plaf.basic.BasicGraphicsUtils.getPreferredButtonSize(BasicGraphicsUtils.java:370)
	at java.desktop/com.apple.laf.AquaButtonUI.getPreferredSize(AquaButtonUI.java:443)
	at java.desktop/javax.swing.JComponent.getPreferredSize(JComponent.java:1680)
	at java.desktop/java.awt.FlowLayout.layoutContainer(FlowLayout.java:609)
	at java.desktop/java.awt.Container.layout(Container.java:1537)
	at java.desktop/java.awt.Container.doLayout(Container.java:1526)
	at java.desktop/java.awt.Container.validateTree(Container.java:1722)
	at java.desktop/java.awt.Container.validateTree(Container.java:1731)
	at java.desktop/java.awt.Container.validateTree(Container.java:1731)
	at java.desktop/java.awt.Container.validateTree(Container.java:1731)
	at java.desktop/java.awt.Container.validate(Container.java:1657)
	at java.desktop/java.awt.Container.validateUnconditionally(Container.java:1694)
	at java.desktop/java.awt.Window.show(Window.java:1040)
	at java.desktop/java.awt.Component.show(Component.java:1716)
	at java.desktop/java.awt.Component.setVisible(Component.java:1663)
	at java.desktop/java.awt.Window.setVisible(Window.java:1021)
	at DarklafDemo.lambda$main$0(DarklafDemo.java:22)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:389)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at com.github.weisj.darklaf.ui.button.DarkButtonBorder.getBorderInsets(DarkButtonBorder.java:178)
	at java.desktop/javax.swing.JComponent.getInsets(JComponent.java:1840)
	at java.desktop/javax.swing.plaf.basic.BasicGraphicsUtils.getPreferredButtonSize(BasicGraphicsUtils.java:370)
	at java.desktop/com.apple.laf.AquaButtonUI.getPreferredSize(AquaButtonUI.java:443)
	at java.desktop/javax.swing.JComponent.getPreferredSize(JComponent.java:1680)
	at java.desktop/java.awt.FlowLayout.layoutContainer(FlowLayout.java:609)
	at java.desktop/java.awt.Container.layout(Container.java:1537)
	at java.desktop/java.awt.Container.doLayout(Container.java:1526)
	at java.desktop/java.awt.Container.validateTree(Container.java:1722)
	at java.desktop/java.awt.Container.validateTree(Container.java:1731)
	at java.desktop/java.awt.Container.validateTree(Container.java:1731)
	at java.desktop/java.awt.Container.validateTree(Container.java:1731)
	at java.desktop/java.awt.Container.validate(Container.java:1657)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2760)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:389)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:389)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by kirill-grouchnikov** [comment]
This is on a MacBook Pro running Catalina (10.15.1)

**Comment by weisJ** [comment]
Could you try this with the latest version. There the error should include which file specifically wasn't found.

**Comment by kirill-grouchnikov** [comment]
No more crashes in the latest I just downloaded.
