### ISSUE TITLE
Tooltip shadow does not seem to use transparent background in macOS in balloon mode

### ISSUE THREAD

**Issue by vlsi** [weisJ/darklaf#51]
darklaf 1.3.3.6:

JMeter:

<img width="133" alt="tooltip_macos_shadow" src="https://user-images.githubusercontent.com/213894/74827088-d3c0b400-531d-11ea-90f4-c2483142e368.png">

TooltipDemo

balloon:
<img width="197" alt="default_tooltip" src="https://user-images.githubusercontent.com/213894/74834162-f063e880-532b-11ea-9612-05a53b91350c.png">

plain:
<img width="208" alt="plain_tooltip" src="https://user-images.githubusercontent.com/213894/74834202-05d91280-532c-11ea-829f-10c94531fd02.png">

**Comment by weisJ** [comment]
Could you tell me if the background is still opaque if the tooltip overlabs the boundary of the parent window?

**Comment by vlsi** [comment]
It is:

<img width="196" alt="tooltip_bounds" src="https://user-images.githubusercontent.com/213894/74840769-987fae80-5338-11ea-8355-0b14c654d90f.png">

**Comment by weisJ** [comment]
What does ````tooltip.isOpaque()````  and ````DarkUIUtil.getWindow(tooltip).getOpacity()```` return for you?

**Comment by vlsi** [comment]
> What does tooltip.isOpaque() and DarkUIUtil.getWindow(tooltip).getOpacity() return for you in each case?

I have added `System.out.println(this.isOpaque() + ", " + DarkUIUtil.getWindow(this).getOpacity())` to `com.github.weisj.darklaf.components.tooltip.DarkToolTip#paint`, and it generates `false, 0.972549`

That is the same for both `plain` and `balloon` cases.
Note: the tooltip appearance seems not to be using any fading. It just flickers for now :-/

**Comment by weisJ** [comment]
> I have added `System.out.println(this.isOpaque() + ", " + DarkUIUtil.getWindow(this).getOpacity())` to `com.github.weisj.darklaf.components.tooltip.DarkToolTip#paint`, and it generates `false, 0.972549`

What about ˋˋˋˋ isLightweight()ˋˋˋˋ?

> Note: the tooltip appearance seems not to be using any fading. It just flickers for now :-/

Please disable it for now by setting ˋˋˋˋalpha = 1.0ˋˋˋˋ and removing the AncestorListener in DarkToolTip.

**Comment by vlsi** [comment]
isLightweight = true

**Comment by weisJ** [comment]
Does adding `setBackground(DarkUIUtil.TRANSPARENT_COLOR)` to the contructor of DarkToolTip change anything?

**Comment by vlsi** [comment]
It does not.

Just in case, `Color.RED` produces
<img width="175" alt="color_red" src="https://user-images.githubusercontent.com/213894/74869679-72263700-5369-11ea-98b4-bc69b7dbbdea.png">

**Comment by weisJ** [comment]
If you make the `paint(Graphics g)` method of DarkToolTip do nothing is the white background still occurring?

**Comment by vlsi** [comment]
Ok, I randomly removed `!toolTip.isLightweight()` from `com.github.weisj.darklaf.ui.tooltip.DarkTooltipUI#hierarchyChanged`, and it more-or-less works now:

<img width="210" alt="Снимок экрана 2020-02-19 в 22 52 21" src="https://user-images.githubusercontent.com/213894/74870266-8585d200-536a-11ea-904e-b0c780f07ed4.png">


```java
    @Override
    public void hierarchyChanged(final HierarchyEvent e) {
        Window w = SwingUtilities.getWindowAncestor(toolTip);
        System.out.println("w = " + w + ", toolTip.isLightweight() " + toolTip.isLightweight() +
            ", !isDecorated(w) " + !isDecorated(w));
        if (w != null && !isDecorated(w)){// && !toolTip.isLightweight() && !isDecorated(w)) {
```

prints the following:

```
toolTip = com.github.weisj.darklaf.components.tooltip.DarkToolTip[,0,0,0x0,invalid,alignmentX=0.0,alignmentY=0.0,border=com.github.weisj.darklaf.ui.tooltip.DarkTooltipBorder@63118de5,flags=16777216,maximumSize=,minimumSize=,preferredSize=java.awt.Dimension[width=137,height=43],tipText=<html><body><nobr>ToolTip demo text!</nobr></body></html>], toolTip.isLightweight() = false, !isDecorated(w) = true
    w = javax.swing.Popup$HeavyWeightWindow[win0,703,488,0x0,invalid,hidden,layout=java.awt.BorderLayout,rootPaneCheckingEnabled=true]
toolTip = com.github.weisj.darklaf.components.tooltip.DarkToolTip[,0,0,0x0,invalid,alignmentX=0.0,alignmentY=0.0,border=com.github.weisj.darklaf.ui.tooltip.DarkTooltipBorder@63118de5,flags=16777216,maximumSize=,minimumSize=,preferredSize=java.awt.Dimension[width=137,height=43],tipText=<html><body><nobr>ToolTip demo text!</nobr></body></html>], toolTip.isLightweight() = true, !isDecorated(w) = true
    w = javax.swing.Popup$HeavyWeightWindow[win0,703,488,1x1,invalid,hidden,layout=java.awt.BorderLayout,rootPaneCheckingEnabled=true]
toolTip = com.github.weisj.darklaf.components.tooltip.DarkToolTip[,0,0,137x43,alignmentX=0.0,alignmentY=0.0,border=com.github.weisj.darklaf.ui.tooltip.DarkTooltipBorder@63118de5,flags=16777216,maximumSize=,minimumSize=,preferredSize=java.awt.Dimension[width=137,height=43],tipText=<html><body><nobr>ToolTip demo text!</nobr></body></html>], toolTip.isLightweight() = true, !isDecorated(w) = true
    w = javax.swing.Popup$HeavyWeightWindow[win0,703,488,137x43,layout=java.awt.BorderLayout,rootPaneCheckingEnabled=true]
alpha = 0.0
paint.this = com.github.weisj.darklaf.components.tooltip.DarkToolTip[,0,0,137x43,alignmentX=0.0,alignmentY=0.0,border=com.github.weisj.darklaf.ui.tooltip.DarkTooltipBorder@63118de5,flags=16777218,maximumSize=,minimumSize=,preferredSize=java.awt.Dimension[width=137,height=43],tipText=<html><body><nobr>ToolTip demo text!</nobr></body></html>], false, 0.972549
alpha = 0.0
paint.this = com.github.weisj.darklaf.components.tooltip.DarkToolTip[,0,0,137x43,alignmentX=0.0,alignmentY=0.0,border=com.github.weisj.darklaf.ui.tooltip.DarkTooltipBorder@63118de5,flags=16777218,maximumSize=,minimumSize=,preferredSize=java.awt.Dimension[width=137,height=43],tipText=<html><body><nobr>ToolTip demo text!</nobr></body></html>], false, 0.972549
alpha = 0.25
paint.this = com.github.weisj.darklaf.components.tooltip.DarkToolTip[,0,0,137x43,alignmentX=0.0,alignmentY=0.0,border=com.github.weisj.darklaf.ui.tooltip.DarkTooltipBorder@63118de5,flags=16777218,maximumSize=,minimumSize=,preferredSize=java.awt.Dimension[width=137,height=43],tipText=<html><body><nobr>ToolTip demo text!</nobr></body></html>], false, 0.972549
alpha = 0.5
paint.this = com.github.weisj.darklaf.components.tooltip.DarkToolTip[,0,0,137x43,alignmentX=0.0,alignmentY=0.0,border=com.github.weisj.darklaf.ui.tooltip.DarkTooltipBorder@63118de5,flags=16777218,maximumSize=,minimumSize=,preferredSize=java.awt.Dimension[width=137,height=43],tipText=<html><body><nobr>ToolTip demo text!</nobr></body></html>], false, 0.972549
alpha = 0.75
paint.this = com.github.weisj.darklaf.components.tooltip.DarkToolTip[,0,0,137x43,alignmentX=0.0,alignmentY=0.0,border=com.github.weisj.darklaf.ui.tooltip.DarkTooltipBorder@63118de5,flags=16777218,maximumSize=,minimumSize=,preferredSize=java.awt.Dimension[width=137,height=43],tipText=<html><body><nobr>ToolTip demo text!</nobr></body></html>], false, 0.972549
alpha = 1.0
paint.this = com.github.weisj.darklaf.components.tooltip.DarkToolTip[,0,0,137x43,alignmentX=0.0,alignmentY=0.0,border=com.github.weisj.darklaf.ui.tooltip.DarkTooltipBorder@63118de5,flags=16777218,maximumSize=,minimumSize=,preferredSize=java.awt.Dimension[width=137,height=43],tipText=<html><body><nobr>ToolTip demo text!</nobr></body></html>], false, 0.972549
toolTip = com.github.weisj.darklaf.components.tooltip.DarkToolTip[,0,0,137x43,alignmentX=0.0,alignmentY=0.0,border=com.github.weisj.darklaf.ui.tooltip.DarkTooltipBorder@63118de5,flags=16777216,maximumSize=,minimumSize=,preferredSize=java.awt.Dimension[width=137,height=43],tipText=<html><body><nobr>ToolTip demo text!</nobr></body></html>], toolTip.isLightweight() = true, !isDecorated(w) = true
    w = javax.swing.Popup$HeavyWeightWindow[win0,703,488,137x43,hidden,layout=java.awt.BorderLayout,rootPaneCheckingEnabled=true]
toolTip = com.github.weisj.darklaf.components.tooltip.DarkToolTip[,0,0,137x43,invalid,alignmentX=0.0,alignmentY=0.0,border=com.github.weisj.darklaf.ui.tooltip.DarkTooltipBorder@63118de5,flags=16777216,maximumSize=,minimumSize=,preferredSize=java.awt.Dimension[width=137,height=43],tipText=<html><body><nobr>ToolTip demo text!</nobr></body></html>], toolTip.isLightweight() = false, !isDecorated(w) = true
    w = javax.swing.Popup$HeavyWeightWindow[win0,703,488,137x43,invalid,hidden,layout=java.awt.BorderLayout,rootPaneCheckingEnabled=true]
toolTip = com.github.weisj.darklaf.components.tooltip.DarkToolTip[,0,0,137x43,invalid,alignmentX=0.0,alignmentY=0.0,border=com.github.weisj.darklaf.ui.tooltip.DarkTooltipBorder@63118de5,flags=16777216,maximumSize=,minimumSize=,preferredSize=java.awt.Dimension[width=137,height=43],tipText=<html><body><nobr>ToolTip demo text!</nobr></body></html>], toolTip.isLightweight() = false, !isDecorated(w) = true
    w = null
```

What I see is `isLightweight() = false` at the very beginning, then it is `true` in the middle, then it switches to `false` again.

**Comment by weisJ** [comment]
Does this also the case for tooltips that are contained in the parent window. If yes it seems like on macOS heavy weight popups are used by default.

**Comment by vlsi** [comment]
> paint(Graphics g) method of DarkToolTip do nothing

<img width="236" alt="Снимок экрана 2020-02-19 в 23 01 17" src="https://user-images.githubusercontent.com/213894/74871066-e19d2600-536b-11ea-8e3d-2c942c25cef3.png">

It is pretty much the same. The box is always painted.

**Comment by vlsi** [comment]
> OverlayScrollPaneDemo

Its animation is way better than tooltip.
Fade-in animation for OverlayScrollPaneDemo scroll looks OK.
Fade-ou animation looks not that good. It looks there's alpha jump at the very beginning of fade-out.

**Comment by vlsi** [comment]
>If yes it seems like on macOS heavy weight popups are used by default.

I logged toolTip.isDisplayable(), and it looks like lightweight=false only appear when `toolTip.isDisplayable()`

**Comment by weisJ** [comment]
Ok, then removing `!toolTip.isLightweight()` from the check should fix the problem. It does not seem to cause any issues with actual lightweight popups.

Could you check if the animations look better now with the newest version?

**Comment by vlsi** [comment]
>Could you check if the animations look better now with the newest version?

It looks a bit better, however, there's notable flickering left.

1) There's "flash of unstyled content" left. That is the very first paint seems to still use opaque background, then it switches to fully transparent

2) If the mouse is moved over the popup while it fades, the popup is flickering.

**Comment by vlsi** [comment]
I have added logging of alpha to `DarkToolTip#paint`, and I get the following:

```java
    @Override
    public void paint(final Graphics g) {
        GraphicsContext config = new GraphicsContext(g);
        System.out.println("alpha = " + alpha);
```

```
alpha = 1.0
alpha = 0.0
alpha = 0.25
alpha = 0.5
alpha = 0.75
alpha = 1.0
```

**Comment by weisJ** [comment]
Could you try again?

**Comment by vlsi** [comment]
The very first fade-in is perfect if I keep the mouse still.
The next ones flicker even if I try keep the mouse still :-/

If I move the mouse just after the very first fade-in starts (==the first fade-in after application start), it is flickering as well.

**Comment by weisJ** [comment]
This could be happening because the tooltip is displayed right under the mouse pointer. When moved swing tries to hide the tooltip, as the mouse is no longer on the corresponding component. Because the LaF doesn't want this to happen it dispatches an event to that tells the tooltip manager to actually show the tooltip. Now because heavyweight windows are used they are disposed in between.

I can somewhat observe the same thing when the tooltip goes outside the frame (though it flickers only briefly).

Could you check what `ToolTipManager.sharedInstance().isLightWeightPopupEnabled()` returns for you? If it is `false` try to set `ToolTipManager.sharedInstance().setLightWeightPopupEnabled(true)`.

**Comment by vlsi** [comment]
ToolTipManager.sharedInstance().isLightWeightPopupEnabled() is always true in DarkToolTip#paint

**Comment by vlsi** [comment]
Ok, I found why the tooltip is always heavyweight.

The thing is `com.apple.laf.AquaLookAndFeel` is still initialized, and it installs its own `com.apple.laf.ScreenPopupFactory` to `PopupFactory.setSharedInstance`.

`ScreenPopupFactory` seems to use platform-specific tools to draw shadow and fade animations, so it goes with heavyweight no matter if the tooltip is inside the window or not.


The initialization of `AquaLookAndFeel` is triggered in `com.github.weisj.darklaf.DarkLaf#initialize` -> `call("initialize")`

Do you think it is expected that `DarkLaf` initializes the default laf?

**Comment by weisJ** [comment]
Initialising the default laf is done so that some platform specific settings are applied i.e. certain shortcuts or rendering presets. Does removing  `call("initialize")` solve the flickering issue? If yes one can save the default PopupFactory and reset it after initialize has been called.

**Comment by vlsi** [comment]
>call("initialize")

Removal of that causes

```
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at java.desktop/javax.swing.UIDefaults.getUI(UIDefaults.java:804)
	at java.desktop/javax.swing.UIManager.getUI(UIManager.java:1067)
	at java.desktop/javax.swing.JCheckBox.updateUI(JCheckBox.java:225)
	at java.desktop/javax.swing.AbstractButton.init(AbstractButton.java:2136)
	at java.desktop/javax.swing.JToggleButton.<init>(JToggleButton.java:177)
	at java.desktop/javax.swing.JCheckBox.<init>(JCheckBox.java:173)
	at java.desktop/javax.swing.JCheckBox.<init>(JCheckBox.java:124)
	at ui.toolTip.ToolTipDemo$1.<init>(ToolTipDemo.java:51)
	at ui.toolTip.ToolTipDemo.createComponent(ToolTipDemo.java:51)
	at ui.ComponentDemo.lambda$showDemo$0(ComponentDemo.java:46)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.NullPointerException
	at java.desktop/com.apple.laf.AquaUtilControlSize$SizeVariant.<init>(AquaUtilControlSize.java:232)
	at java.desktop/com.apple.laf.AquaUtilControlSize$SizeDescriptor.<init>(AquaUtilControlSize.java:173)
	at java.desktop/com.apple.laf.AquaButtonCheckBoxUI$CheckBoxButtonBorder.<init>(AquaButtonCheckBoxUI.java:62)
Caused by: java.lang.NullPointerException

	at java.desktop/com.apple.laf.AquaButtonCheckBoxUI.getPainter(AquaButtonCheckBoxUI.java:57)
	at java.desktop/com.apple.laf.AquaButtonLabeledUI.<init>(AquaButtonLabeledUI.java:61)
	at java.desktop/com.apple.laf.AquaButtonCheckBoxUI.<init>(AquaButtonCheckBoxUI.java:36)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:166)
	at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:404)
	at java.base/java.lang.Class.newInstance(Class.java:591)
	at java.desktop/com.apple.laf.AquaUtils$RecyclableSingletonFromDefaultConstructor.getInstance(AquaUtils.java:181)
	at java.desktop/com.apple.laf.AquaUtils$RecyclableSingleton.lambda$get$0(AquaUtils.java:159)
	at java.desktop/sun.awt.AppContext.getSoftReferenceValue(AppContext.java:898)
	at java.desktop/com.apple.laf.AquaUtils$RecyclableSingleton.get(AquaUtils.java:159)
	at java.desktop/com.apple.laf.AquaButtonCheckBoxUI.createUI(AquaButtonCheckBoxUI.java:45)
	... 27 more
```

**Comment by vlsi** [comment]
>If yes one can save the default PopupFactory and reset it after initialize has been called.

I don't think it is safe that `popupFactory` can outlive its LAF.

**Comment by weisJ** [comment]
Well we only need to change
````java
call("initialize");
````
to
````java
PopupFactory popupFactory = PopupFactory.getSharedInstance();
call("initialize");
PopupFactory.setSharedInstance(popupFactory);
````

**Comment by vlsi** [comment]
>call("initialize");
>PopupFactory.setSharedInstance(new PopupFactory());

This indeed heals in-window popup. It becomes much smoother.

**Comment by weisJ** [comment]
Sadly I haven't yet found a solution for heavy weight tooltips. The implementation of ToolTipManager is rather eager to hide tooltips even when it wouldn't be necessary.

**Comment by weisJ** [comment]
@vlsi how do heavyweight popups behave for you with the newest version?

**Comment by vlsi** [comment]
heavyweight ones flicker once.

That is at the beginning of fade-in it blinks, and then starts appearing again.

**Comment by weisJ** [comment]
Would you mind sharing a screen capture of it? How does it behave when moving the cursor between the the tooltip and the button (after it has already been displayed)?

**Comment by vlsi** [comment]
Here's the recording: https://drive.google.com/open?id=1QxJ-i9FtCjjmjIuMl05FbOPZ6-qteQ9e

Note: you'd better download the raw `.mov` file as youtube preview differs significantly from the original.

**Comment by weisJ** [comment]
@vlsi is this issue still present?

**Comment by vlsi** [comment]
Now it crashes when trying to show a popup in ToolTip demo with a narrow window.

```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at com.github.weisj.darklaf.platform.macos.ui.MacOSTitlePane.getPreferredSize(MacOSTitlePane.java:191)
	at com.github.weisj.darklaf.ui.rootpane.DarkSubstanceRootLayout.preferredLayoutSize(DarkSubstanceRootLayout.java:89)
	at java.awt.Container.preferredSize(Container.java:1799)
	at java.awt.Container.getPreferredSize(Container.java:1783)
	at javax.swing.JComponent.getPreferredSize(JComponent.java:1664)
	at java.awt.BorderLayout.preferredLayoutSize(BorderLayout.java:719)
	at java.awt.Container.preferredSize(Container.java:1799)
	at java.awt.Container.getPreferredSize(Container.java:1783)
	at javax.swing.PopupFactory$ContainerPopup.pack(PopupFactory.java:529)
	at javax.swing.PopupFactory$MediumWeightPopup.reset(PopupFactory.java:961)
	at javax.swing.PopupFactory$MediumWeightPopup.getMediumWeightPopup(PopupFactory.java:835)
	at javax.swing.PopupFactory.getMediumWeightPopup(PopupFactory.java:266)
	at javax.swing.PopupFactory.getPopup(PopupFactory.java:231)
	at javax.swing.PopupFactory.getPopup(PopupFactory.java:174)
	at com.github.weisj.darklaf.DarkLaf$1.getPopup(DarkLaf.java:360)
	at javax.swing.ToolTipManager.showTipWindow(ToolTipManager.java:342)
	at javax.swing.ToolTipManager$insideTimerAction.actionPerformed(ToolTipManager.java:669)
	at javax.swing.Timer.fireActionPerformed(Timer.java:313)
	at javax.swing.Timer$DoPostEvent.run(Timer.java:245)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at com.github.weisj.darklaf.platform.macos.ui.MacOSTitlePane.getPreferredSize(MacOSTitlePane.java:191)
	at com.github.weisj.darklaf.ui.rootpane.DarkSubstanceRootLayout.preferredLayoutSize(DarkSubstanceRootLayout.java:89)
	at java.awt.Container.preferredSize(Container.java:1799)
	at java.awt.Container.getPreferredSize(Container.java:1783)
	at javax.swing.JComponent.getPreferredSize(JComponent.java:1664)
	at java.awt.BorderLayout.preferredLayoutSize(BorderLayout.java:719)
	at java.awt.Container.preferredSize(Container.java:1799)
	at java.awt.Container.getPreferredSize(Container.java:1783)
	at javax.swing.PopupFactory$ContainerPopup.pack(PopupFactory.java:529)
	at javax.swing.PopupFactory$MediumWeightPopup.reset(PopupFactory.java:961)
	at javax.swing.PopupFactory$MediumWeightPopup.getMediumWeightPopup(PopupFactory.java:835)
	at javax.swing.PopupFactory.getMediumWeightPopup(PopupFactory.java:266)
	at javax.swing.PopupFactory.getPopup(PopupFactory.java:231)
	at javax.swing.PopupFactory.getPopup(PopupFactory.java:174)
	at com.github.weisj.darklaf.DarkLaf$1.getPopup(DarkLaf.java:360)
	at javax.swing.ToolTipManager.showTipWindow(ToolTipManager.java:342)
	at javax.swing.ToolTipManager.mouseMoved(ToolTipManager.java:605)
	at java.awt.AWTEventMulticaster.mouseMoved(AWTEventMulticaster.java:330)
	at java.awt.Component.processMouseMotionEvent(Component.java:6584)
	at javax.swing.JComponent.processMouseMotionEvent(JComponent.java:3342)
	at java.awt.Component.processEvent(Component.java:6308)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4548)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by weisJ** [comment]
Fixed. The decorations should even have been installed on popups in the first place.

**Comment by vlsi** [comment]
Thanks, NPE is gone.
Now the behavior is the same as in https://github.com/weisJ/darklaf/issues/51#issuecomment-589187134

It does flicker right at the very start of the fade-in.
It flickers every time (I don't need to restart the app to reproduce it)

**Comment by weisJ** [comment]
I'm moving the discussion to #82 as the original issue has been resolved.
