### ISSUE TITLE
DarkTextUI cannot access class sun.swing.DefaultLookup

### ISSUE THREAD

**Issue by vlsi** [weisJ/darklaf#59]
Ran DialogDemo with `--illegal-access=deny`
Got the following:

```
Exception in thread "AWT-EventQueue-0" java.lang.IllegalAccessError: class com.github.weisj.darklaf.ui.text.DarkTextUI (in unnamed module @0x68ceda24) cannot access class sun.swing.DefaultLookup (in module java.desktop) because module java.desktop does not export sun.swing to unnamed module @0x68ceda24
	at com.github.weisj.darklaf.ui.text.DarkTextUI.getInputMap(DarkTextUI.java:215)
	at com.github.weisj.darklaf.ui.text.DarkTextUI.installKeyboardActions(DarkTextUI.java:175)
	at java.desktop/javax.swing.plaf.basic.BasicTextUI.installUI(BasicTextUI.java:841)
	at com.github.weisj.darklaf.ui.text.DarkTextUI.installUI(DarkTextUI.java:194)
	at com.github.weisj.darklaf.ui.text.DarkFormattedTextFieldUI.installUI(DarkFormattedTextFieldUI.java:55)
	at java.desktop/javax.swing.JComponent.setUI(JComponent.java:685)
	at java.desktop/javax.swing.text.JTextComponent.setUI(JTextComponent.java:342)
	at java.desktop/javax.swing.text.JTextComponent.updateUI(JTextComponent.java:352)
	at java.desktop/javax.swing.text.JTextComponent.<init>(JTextComponent.java:326)
	at java.desktop/javax.swing.JTextField.<init>(JTextField.java:230)
	at java.desktop/javax.swing.JTextField.<init>(JTextField.java:171)
	at java.desktop/javax.swing.JFormattedTextField.<init>(JFormattedTextField.java:293)
	at java.desktop/javax.swing.JFormattedTextField.<init>(JFormattedTextField.java:306)
	at ui.dialog.CustomDialog.<init>(CustomDialog.java:62)
	at ui.dialog.DialogDemo.<init>(DialogDemo.java:57)
	at ui.dialog.DialogDemo.createAndShowGUI(DialogDemo.java:402)
```

**Comment by weisJ** [comment]
This needs to be fixed in a bigger effort to be compliant with the java 9 module system. Some things probably will need to be depended on the application using the project adding certain jvm flag.

**Comment by weisJ** [comment]
Closing in favor of #171.
