### ISSUE TITLE
NPE at  com.github.weisj.darklaf.platform.macos.ui.MacOSTitlePane$PropertyChangeHandler.propertyChange(MacOSTitlePane.java:246)

### ISSUE THREAD

**Issue by FoxyBOA** [weisJ/darklaf#63]
We're using 3rd party swing based framework that manipulates UI controls through reflection.

Unfortunately, last release (1.4.0.0) leads to NPE with the following call stack:
```
java.lang.NullPointerException
	at com.github.weisj.darklaf.platform.macos.ui.MacOSTitlePane$PropertyChangeHandler.propertyChange(MacOSTitlePane.java:246)
	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
	at java.awt.Component.firePropertyChange(Component.java:8434)
	at java.awt.Frame.setTitle(Frame.java:523)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
... 3rd party framework call stack
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
... 3rd party framework call stack
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

Based on MacOSTitlePane I suppose that pce.getNewValue() is null at line 246 at correct code could be

```
    protected class PropertyChangeHandler implements PropertyChangeListener {
        public void propertyChange(final PropertyChangeEvent pce) {
            String name = pce.getPropertyName();
            if ("title".equals(name)) {
                titleLabel.setText(pce.getNewValue() == null ? null : pce.getNewValue().toString());
                repaint();
            }
        }
    }

```

P.S. I don't understand why the title value is null, I pass not null value to the framework

**Comment by weisJ** [comment]
Fixed with [`1.4.0.1`](https://github.com/weisJ/darklaf/releases/tag/v1.4.0.1).

> P.S. I don't understand why the title value is null, I pass not null value to the framework

Well the LaF definitely doesn't set titles anywhere so my best guess would be that the 3rd party library you are using sets a `null` title somewhere temporarily.

**Comment by FoxyBOA** [comment]
Tested in version 1.4.0.1 The issue is active (i.e I still have NPE).

The only option I see is that titleLabel is null. Any ideas on how that can be (e.g. property change calls before initialization of the titleLabel)?

**Comment by FoxyBOA** [comment]
Fixed. Thank you!
