### ISSUE TITLE
NPE in DarkTreeCellRenderer.unwrapBooleanIfPossible

### ISSUE THREAD

**Issue by vlsi** [weisJ/darklaf#66]
darklaf-core-1.4.0.3.jar, Java 1.8

```java
        if (val instanceof DefaultMutableTreeNode) {
            val = ((DefaultMutableTreeNode) val).getUserObject();
        }
        if (!(val instanceof Boolean)) {
            String str = val.toString();  <-- NPE here
```

```
Caused by: java.lang.NullPointerException
	at com.github.weisj.darklaf.ui.tree.DarkTreeCellRenderer.unwrapBooleanIfPossible(DarkTreeCellRenderer.java:74) ~[darklaf-core-1.4.0.3.jar:1.4.0.3]
	at com.github.weisj.darklaf.ui.tree.DarkTreeCellRenderer.getTreeCellRendererComponent(DarkTreeCellRenderer.java:49) ~[darklaf-core-1.4.0.3.jar:1.4.0.3]
	at javax.swing.plaf.basic.BasicTreeUI$NodeDimensionsHandler.getNodeDimensions(BasicTreeUI.java:2807) ~[?:1.8.0_222]
	at javax.swing.tree.AbstractLayoutCache.getNodeDimensions(AbstractLayoutCache.java:492) ~[?:1.8.0_222]
	at javax.swing.tree.VariableHeightLayoutCache$TreeStateNode.updatePreferredSize(VariableHeightLayoutCache.java:1360) ~[?:1.8.0_222]
	at javax.swing.tree.VariableHeightLayoutCache.rebuild(VariableHeightLayoutCache.java:738) ~[?:1.8.0_222]
	at javax.swing.tree.VariableHeightLayoutCache.setModel(VariableHeightLayoutCache.java:109) ~[?:1.8.0_222]
	at javax.swing.plaf.basic.BasicTreeUI.setModel(BasicTreeUI.java:412) ~[?:1.8.0_222]
	at javax.swing.plaf.basic.BasicTreeUI$Handler.propertyChange(BasicTreeUI.java:3414) ~[?:1.8.0_222]
	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335) ~[?:1.8.0_222]
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327) ~[?:1.8.0_222]
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263) ~[?:1.8.0_222]
	at java.awt.Component.firePropertyChange(Component.java:8434) ~[?:1.8.0_222]
	at javax.swing.JTree.setModel(JTree.java:885) ~[?:1.8.0_222]
	at javax.swing.JTree.<init>(JTree.java:673) ~[?:1.8.0_222]
```

**Comment by weisJ** [comment]
Should be fixed now

**Comment by vlsi** [comment]
Fixed
