### ISSUE TITLE
NPE in ScrollLayoutManagerDelegate.addLayoutComponent

### ISSUE THREAD

**Issue by vlsi** [weisJ/darklaf#68]
```
java.lang.NullPointerException: null
	at javax.swing.ScrollPaneLayout.addSingletonComponent(ScrollPaneLayout.java:202) ~[?:1.8.0_222]
	at javax.swing.ScrollPaneLayout.addLayoutComponent(ScrollPaneLayout.java:254) ~[?:1.8.0_222]
	at com.github.weisj.darklaf.ui.scrollpane.ScrollLayoutManagerDelegate.addLayoutComponent(ScrollLayoutManagerDelegate.java:49) ~[darklaf-core.jar:1.4.0.3-SNAPSHOT]
	at java.awt.Container.addImpl(Container.java:1132) ~[?:1.8.0_222]
	at java.awt.Container.add(Container.java:975) ~[?:1.8.0_222]
	at javax.swing.JScrollPane.setCorner(JScrollPane.java:1267) ~[?:1.8.0_222]
	at javax.swing.JTable.configureEnclosingScrollPaneUI(JTable.java:792) ~[?:1.8.0_222]
	at javax.swing.JTable.updateUI(JTable.java:3649) ~[?:1.8.0_222]
	at javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1238) ~[?:1.8.0_222]
	at javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1253) ~[?:1.8.0_222]
	at javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1253) ~[?:1.8.0_222]
	at javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1253) ~[?:1.8.0_222]
	at javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1253) ~[?:1.8.0_222]
	at javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1253) ~[?:1.8.0_222]
	at javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1253) ~[?:1.8.0_222]
	at javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1253) ~[?:1.8.0_222]
	at javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1253) ~[?:1.8.0_222]
	at javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1253) ~[?:1.8.0_222]
	at javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1253) ~[?:1.8.0_222]
	at javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1253) ~[?:1.8.0_222]
	at javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1253) ~[?:1.8.0_222]
	at javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1253) ~[?:1.8.0_222]
	at javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1253) ~[?:1.8.0_222]
	at javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1253) ~[?:1.8.0_222]
	at javax.swing.SwingUtilities.updateComponentTreeUI(SwingUtilities.java:1229) ~[?:1.8.0_222]
	at com.github.weisj.darklaf.LafManager.updateLafRecursively(LafManager.java:194) ~[darklaf-core.jar:1.4.0.3-SNAPSHOT]
	at com.github.weisj.darklaf.LafManager.updateLaf(LafManager.java:186) ~[darklaf-core.jar:1.4.0.3-SNAPSHOT]
	at com.github.weisj.darklaf.LafManager.install(LafManager.java:172) ~[darklaf-core.jar:1.4.0.3-SNAPSHOT]
	at com.github.weisj.darklaf.LafManager.installTheme(LafManager.java:140) ~[darklaf-core.jar:1.4.0.3-SNAPSHOT]
	at org.apache.jmeter.gui.action.LookAndFeelCommand.activateLookAndFeel(LookAndFeelCommand.java:204) ~[ApacheJMeter_core.jar:5.3-SNAPSHOT]
	at org.apache.jmeter.gui.action.LookAndFeelCommand.doAction(LookAndFeelCommand.java:225) ~[ApacheJMeter_core.jar:5.3-SNAPSHOT]
	at org.apache.jmeter.gui.action.ActionRouter.performAction(ActionRouter.java:87) ~[ApacheJMeter_core.jar:5.3-SNAPSHOT]
	at org.apache.jmeter.gui.action.ActionRouter.lambda$actionPerformed$0(ActionRouter.java:69) ~[ApacheJMeter_core.jar:5.3-SNAPSHOT]
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311) [?:1.8.0_222]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758) [?:1.8.0_222]
	at java.awt.EventQueue.access$500(EventQueue.java:97) [?:1.8.0_222]
	at java.awt.EventQueue$3.run(EventQueue.java:709) [?:1.8.0_222]
	at java.awt.EventQueue$3.run(EventQueue.java:703) [?:1.8.0_222]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_222]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74) [?:1.8.0_222]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728) [?:1.8.0_222]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205) [?:1.8.0_222]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [?:1.8.0_222]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [?:1.8.0_222]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:1.8.0_222]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [?:1.8.0_222]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [?:1.8.0_222]
```

**Comment by weisJ** [comment]
Do you have an example to reproduce the issue? Looks like the component that gets removed has no parent which produces the NPE.

**Comment by vlsi** [comment]
The reproducer is as follows:

```
$ git clone https://github.com/weisJ/darklaf.git
$ git clone --branch darklaf https://github.com/vlsi/jmeter.git
$ cd jmeter
$ ./gradlew runGui -PlocalDarklaf
```

It will launch JMeter. Then in the `Options -> Look and Feel` you can change between Darklaf themes, and NPE is thrown at the very first chage.

The logs are printed to `bin/jmeter.log`.

I've added try-catch to `ScrollLayoutManagerDelegate`, and it prints as follows:

```java
    @Override
    public void addLayoutComponent(final String name, final Component comp) {
        try {
        delegate.addLayoutComponent(name, comp);
        } catch(NullPointerException e) {
          System.out.println("NPE in ScrollLayoutManagerDelegate.addLayoutComponent: " + name + ", " + comp);
//          throw e;
        }
    }
```

```
NPE in ScrollLayoutManagerDelegate.addLayoutComponent: UPPER_RIGHT_CORNER, com.github.weisj.darklaf.ui.table.DarkTableHeaderCorner[,0,0,0x0,invalid,alignmentX=0.0,alignmentY=0.0,border=,flags=0,maximumSize=,minimumSize=,preferredSize=]
NPE in ScrollLayoutManagerDelegate.addLayoutComponent: UPPER_RIGHT_CORNER, com.github.weisj.darklaf.ui.table.DarkTableHeaderCorner[,0,0,0x0,invalid,alignmentX=0.0,alignmentY=0.0,border=,flags=0,maximumSize=,minimumSize=,preferredSize=]
```

**Comment by weisJ** [comment]
Apparently there is some funky business going on where the corner component gets set but the parent doesn't change. `ScrollLayoutManager` assumes that any installed component must  have a parent that it tries to remove the component from when a new one is set. Sadly I could not reproduce the issue in a minimal example and it isn't that easy to hunt down the point where the parent gets set to `null` as this completely happens outside the Laf. The fix now just checks whether the parent of the old component is null and simply removes it before setting the new component, which circumvents the whole process.
