### ISSUE TITLE
Table and tree: skip editing for keys like META, CAPS_LOCK and so on 

### ISSUE THREAD

**Issue by vlsi** [weisJ/darklaf#90]
META is very commonly used in macOS (e.g. `ctrl+c` is `cmd+c` which is `meta+c`), and table starts editing when `meta` is pressed.

AFAIK it is [fixed in Java 13+](https://github.com/openjdk/jdk/commit/768ef3cd20d41aae33af3e729282a8eb486da180#diff-40e82c6d5f7585b9203ec531c8288905R5281-R5282), however, I suggest to fix it at LaF level as well.

For instance, ignore `KeyEvent.VK_ALT_GRAPH`, `KeyEvent.VK_META`, `KeyEvent.VK_CAPS_LOCK` in `com.github.weisj.darklaf.ui.table.DarkTableCellEditor#isCellEditable` and `com.github.weisj.darklaf.ui.tree.DarkTreeCellEditor#isCellEditable`

**Comment by weisJ** [comment]
This also applies for the windows key on windows. Though the better solution is to avoid starting to edit check the condition in the table ui, as this also solves the problem for external cell editors.

**Comment by weisJ** [comment]
Should be fixed now.

**Comment by vlsi** [comment]
A couple of keys more: VK_PRINTSCREEN, VK_NUM_LOCK, VK_SCROLL_LOCK

I'm not sure re VK_CONTEXT_MENU. Is it worth ignoring as well?

One more issue is copy-paste: cmd+c starts to edit instead of copying :(

**Comment by weisJ** [comment]
I have added the key codes. Also any key combination that involves the control/cmd key is now ignored. Am I missing scenarios in which I'd actually want to edit the cell in which I need to press control/cmd?

**Comment by vlsi** [comment]
>Am I missing scenarios in which I'd actually want to edit the cell in which I need to press control/cmd?

`paste`?
I would expect cmd+v (or shift+ins) to overwrite the contents of the cell.

PS. cmd+c starts editing for me in f51aa03648f8d86fd2e369451e8b143655e8b90e

**Comment by weisJ** [comment]
I have changed it such that only `ctrl/cmd + c` is ignored. Also it should work on macOS now.

**Comment by vlsi** [comment]
Eh.
event.getModifiersEx() produces 256 for cmd+c, and it is not compatible with `Toolkit.getDefaultToolkit().getMenuShortcutKeyMask()`

Note: `MenuShortcutKeyMask` is `ctrl`, however default copy action is bound to `cmd+c`.

I have not debugged it much, but have you tried capturing `copy` action by binding it via keymap to the default copy action?

---

My external keyboard is https://www.realforce.co.jp/en/products/104U-S_XF01T0/index.html which is not really mac-specific, so I'm not sure how relevant it is, but `num lock` key produces 12 keyCode (==`VK_CLEAR` in JDK13 O_O).

**Comment by weisJ** [comment]
I'm now checking against the the associated action with the key stroke the event produces to determine whether it is the cut/copy action. Hopefully this works on macOS. On windows `ctrl c` is ignored without the fix so I can't test it.

**Comment by vlsi** [comment]
```
[2020-03-20 17:02:29] [SEVERE] Could not load intellij/intellij_mac.properties.properties. inStream parameter is null [at com.github.weisj.darklaf.theme.Theme]
                     [Details] java.base/java.util.Objects.requireNonNull(Objects.java:247),
                               java.base/java.util.Properties.load(Properties.java:404),
                               com.github.weisj.darklaf.theme.Theme.loadWithClass(Theme.java:230),
                               com.github.weisj.darklaf.theme.Theme.load(Theme.java:217),
                               com.github.weisj.darklaf.theme.IntelliJTheme.loadPlatformProperties(IntelliJTheme.java:42),
                               com.github.weisj.darklaf.DarkLaf.loadThemeDefaults(DarkLaf.java:224),
                               com.github.weisj.darklaf.DarkLaf.getDefaults(DarkLaf.java:112),
                               java.desktop/javax.swing.UIManager.setLookAndFeel(UIManager.java:587),
                               java.desktop/javax.swing.UIManager.setLookAndFeel(UIManager.java:633),
                               com.github.weisj.darklaf.LafManager.install(LafManager.java:171),
                               ui.ComponentDemo.lambda$showDemo$0(ComponentDemo.java:43),
                               java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313),
                               java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770),
                               java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721),
                               java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715),
                               java.base/java.security.AccessController.doPrivileged(AccessController.java:391),
                               java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege
```

**Comment by weisJ** [comment]
I accidentally removed the wrong method in `IntelliJTheme`. Should be fine now.

**Comment by vlsi** [comment]
```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at com.github.weisj.darklaf.ui.table.DarkTableUI.ignoreKeyCodeOnEdit(DarkTableUI.java:437)
	at com.github.weisj.darklaf.ui.table.DarkTableCellEditor.isCellEditable(DarkTableCellEditor.java:183)
	at java.desktop/javax.swing.JTable.editCellAt(JTable.java:3507)
	at java.desktop/javax.swing.JTable.processKeyBinding(JTable.java:5290)
	at java.desktop/javax.swing.JComponent.processKeyBindings(JComponent.java:2962)
	at java.desktop/javax.swing.JComponent.processKeyEvent(JComponent.java:2862)
	at java.desktop/java.awt.Component.processEvent(Component.java:6413)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5012)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
	at java.desktop/java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1950)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:870)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1139)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:1009)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:835)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4893)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2762)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by vlsi** [comment]
stroke == "meta pressed C"

However, none of the `table.getInputMap` (WHEN_IN_FOCUSED_WINDOW, WHEN_FOCUSED, WHEN_ANCESTOR_OF_FOCUSED_COMPONENT) recognizes that keystroke.

**Comment by vlsi** [comment]
<img width="730" alt="Снимок экрана 2020-03-20 в 17 22 10" src="https://user-images.githubusercontent.com/213894/77172652-62685280-6acf-11ea-8179-8465f496dbdc.png">

**Comment by weisJ** [comment]
I have added `meta C/V/X` to the input map of `JTable`. Does this fix it?

**Comment by vlsi** [comment]
`ctrl pressed C`-style inputmap comes from `com.github.weisj.darklaf.ui.table.TableUIBridge#getInputMap`

Still need to figure out where it comes initially.

**Comment by weisJ** [comment]
You are looking for `DarkLaf#installIdeaDefaults`

**Comment by vlsi** [comment]
https://github.com/weisJ/darklaf/blob/233870523b2fe7b76db5de18bf9d9104cad56b2e/core/src/main/java/com/github/weisj/darklaf/DarkLaf.java#L328-L330

I believe it should use CTRL_DOWN_MASK or META_DOWN_MASK depending on isMac.

**Comment by vlsi** [comment]
Oh.
Now `cmd+c` copies the full row (even in single-cell selection mode)
And `cmd+v` does nothing (I would expect it to paste into the cell)

**Comment by weisJ** [comment]
> Oh.
> Now `cmd+c` copies the full row (even in single-cell selection mode)

Does not happen on windows.

> And `cmd+v` does nothing (I would expect it to paste into the cell)

I don't think `JTables` are designed to support this out of the box. There is no mechanism to actually parse the input i.e. anything coming from the clipboard is - without creating an own transferable implementation for the object - a `String`. Now table data is only present in `Object` form. No way to check that the table actually only holds strings (it most likely won't).

So paste is something the user of the `JTable` has to implement.

**Comment by vlsi** [comment]
Apparently, the bug affects not just darklaf, so there should probably in-app workaround of this :-/

**Comment by weisJ** [comment]
> Apparently, the bug affects not just darklaf, so there should probably be an in-app workaround of this issue :-/

Are you referring to the whole row being copied or the pasting issue?

**Comment by vlsi** [comment]
>Are you referring to the whole row being copied or the pasting issue?

I guess to all the things, including `skip editing for keys like META, CAPS_LOCK and so on`.

Of course, there's a question if it is really worth supporting multiple different LaFs. For instance, I doubt there is a great amount of CDE/Motif users.

However, I just tried Metal, and it has the same issue: `meta` starts the edit in the table :-(

**Comment by weisJ** [comment]
I see. However it’s not that surprising as all lafs use the same bindings and actions as `BasicLookAndFeek`.
Could you assess what keys still cause issues? I still think it’s worth it to fix those in darklaf itself. I’ll also look into what might cause the whole row being copied on macOS.

**Comment by vlsi** [comment]
>Could you assess what keys still cause issues? 

8251875d3a11255971103b7fd209314f436369ea

`ESC` VK_ESCAPE

---

Below buttons are probably esoteric:

`INSERT` (notebook does not have that key), and insert on the external keyboard produces `VK_HELP` (no idea why)
`fn` (which is the most left and most bottom key on the notebook). It produces `keyCode==0`, modifiers=0, etc. There might be useful keys with `keyCode=0`, so I'm not sure if it is worth ignoring it.

**Comment by weisJ** [comment]
I think its safe to ignore `INSERT`, `VK_HELP` and `ESC`. As for the copying of the whole row regardless of selection mode you might want to look into `TableUIBridge.TableTransferHandler#createTansferable` as there is no way for me to simulate what's happening there on macOS.
